### ISSUE TITLE
Migrate fully from DCMI Terms to DCAT where possible

### ISSUE THREAD

**Issue by clange** [International-Data-Spaces-Association/InformationModel#112]
Some our terms are defined as refinements of DCMI Terms, others of DCAT. However, much of DCAT is also defined by refining DCMI Terms. Thus, wherever and whenever information model terms refer to DCMI Terms but there is actually a compatible or more specific term in DCAT, the information model should rely on DCAT instead of DCMI Terms.

**Comment by clange** [comment]
@JohannesLipp could you please give this a quick check from your perspective of #109 ? Maybe we have done this already.

**Comment by JohannesLipp** [comment]
Info: We do define the prefix `<http://purl.org/dc/dcmitype/>` in 10 files, but never acually use it. Therefore, I will remove these prefixes as the conceptual updates were already resolved by #109
