### ISSUE TITLE
Property for how to map a Resource or Representation to RDF

### ISSUE THREAD

**Issue by clange** [International-Data-Spaces-Association/InformationModel#144]
We recommend representing the content/payload of Resources (or their Representations) in RDF, but we don't want to force people to do so. However, for interoperability/semantics it might be desirable to specify that a certain resource _could_ be mapped to an RDF if needed. This property, with domain probably (Resource union Representation), could have as its range the URI of, e.g., an RML mapping (e.g., from CSV, XML or JSON to RDF).

**Comment by HaydarAk** [comment]
If I understand you correctly, you would like to add, e.g., a (datatype) property like

```
ids:conformsToRDFMapping a owl:DatatypeProperty
rdfs:domain [ rdf:type owl:Class ;
                owl:unionOf ( ids:Resource ids:Representation)
              ] ;
rdfs:range xsd:anyURI
...
```

to say "this resource / representation is mapped to a rdf found behind this IRI" 

Right?

**Comment by JohannesLipp** [comment]
This is a very interesting research topic, but indeed needs a properly designed use-case to be pursued. 

Therefore: Closed due to inactivity. Please comment & reopen, if still relevant. Thank you!
