### ISSUE TITLE
Measure the coverage of SHACL shapes for validation of the Information Model

### ISSUE THREAD

**Issue by HaydarAk** [International-Data-Spaces-Association/InformationModel#147]
It would be good to have statistics (preferably generated automatically) on how much percent of the information model is covered by SHACL shapes and therefore validatable. 

Could be done with a simple script. 
We usually have a SHACL shape for each class in the Information Model.

**Comment by changqin26** [comment]
We usually have a SHACL shape for each class in the Information Model.---Do we already have a SHACL shape for each class in IM? No missing part?

**Comment by HaydarAk** [comment]
Our motivation for this issue was to check whether there might be some missing shapes.
It has happened before that major changes were made to the information model without adjusting / adding the corresponding SHACL classes.  We could do the checking on class level -> check for existing IDS classes in our ontology if there is a corresponding shacl shape in the testing directory. 
A rather simple approach would be to use a simple RDF / OWL framework to parse the ontology, get all relevant (ids) classes and check, if there is a corresponding shacl shape in the `testing`, subdirectory. 
Usually, we define shapes as follows:

```
shapes:someShapeName
	a sh:NodeShape ; 
	sh:targetClass ids:SomeIDSclassname ;
...
```

therefore, one could possibly retrieve and read all shacl shapes of the testing subdir, check for each IDS class (from the ontology) wether there is a corresponding triple. E.g. for the [ids:Message](https://github.com/International-Data-Spaces-Association/InformationModel/blob/develop/model/communication/Message.ttl), there should be a SHACL shape in the testing subdir with the triple `____ sh:targetClass ids:Message .` .

**Comment by changqin26** [comment]
Thanks for your reply! that is exactly what I want to know. I would like to take over the part of job. I know Matthias has worked on this before, I will firstly check with him and begin to work on the missing shapes.

**Comment by HaydarAk** [comment]
Great! Thank you :)
