### ISSUE TITLE
Complex string value for rightOperand doesn't look right to me

### ISSUE THREAD

**Issue by clange** [International-Data-Spaces-Association/InformationModel#153]
The object of the following triple looks strange to me. I think it includes some stuff that's actually _left_ operands:
https://github.com/IndustrialDataSpace/InformationModel/blob/a3ece467832101a0eecf5f938b3c4ebf6a2ccdd9/examples/TEMPERATURE_RESOURCE.json#L91

**Comment by HaydarAk** [comment]
Contracts have been updated in v3.0.0. RightOperands do not LeftOperand Values anymore.
