### ISSUE TITLE
Support non-IDS properties for domain-specific structure/semantics

### ISSUE THREAD

**Issue by clange** [International-Data-Spaces-Association/InformationModel#190]
Once the Java code generator supports namespaces outside of IDS, we can implement the use of VoID, SHACL and Data Cube properly. We need the following properties:

* SHACL: only `sh:shapesGraph` – but it makes sense to continue having `ids:shapesGraph` as a subproperty, because of the more specific domain ids:DescribedSemantically. However @HaydarAk declaring `ids:shapesGraph` as a datatype property with range `xsd:anyURI` is abusive – please define it as an object property and leave the range unspecified. `sh:shapesGraph` already has the suitable range `owl:Ontology`.

* VoID: The current (temporarily introduced) artificial construct "data resource has `ids:domainVocabulary` of type `ids:VocabularyData`, which then has various VoID properties" is slightly abusing VoID. Most relevant VoID properties have `rdfs:domain void:Dataset`, i.e., they should be attached directly to the IDS data resource. (Thus, any IDS resource and/or representation should be a subclass of `void:Dataset`.) We need:
  * many of the properties that have `rdfs:domain void:Dataset`, i.e.:
    * `void:vocabulary`
    * `void:class`
    * `void:classes`
    * `void:classPartition`
    * `void:properties`
    * `void:property`
    * `void:propertyPartition`
    * `void:distinctObjects`
    * `void:distinctSubjects`
    * `void:subset`
    * `void:rootResource`
  * note that other properties also have `rdfs:domain void:Dataset`, but the IDS infomodel already supports the same mechanisms natively, so I'd say we don't need support for these properties. ( @JohannesLipp in a later phase, we could, for the purpose of documentation and interoperability, provide some axioms that align the native infomodel mechanisms with these features of VoID )
    * `void:feature`
    * `void:sparqlEndpoint`
    * `void:exampleResource`
    * `void:dataDump`
    * `void:uriLookupEndpoint`
    * `void:openSearchDescription` (not sure that this is specifically supported, but I think it's a special case of something that we already support in general)
  * further properties having `rdfs:domain void:Dataset` but not related to structure/semantics but which are, to my understanding, not yet supported by the IDS infomodel, so we should consider adding this functionality to the IDS infomodel ( @JohannesLipp @HaydarAk could you please give me feedback?)
    * `void:uriRegexPattern`
    * `void:uriSpace`
    * `void:documents` – this is once more something for which we might want to consider adding it to the IDS infomodel.
    * `void:entities` – consider adding to IDS infomodel
    * `void:triples`

* Data Cube: The relevant class is `qb:DataSet`. Once more, IDS resource and representation should be subclasses of that. We need the following properties having `rdfs:domain qb:DataSet`:
  * `qb:slice`
  * `qb:structure`

**Comment by sebbader** [comment]
I think we have all the building blocks now. The [examples](https://github.com/International-Data-Spaces-Association/InformationModel/tree/develop/examples/queries-using-sparql/SparqlQueries/src/main/resources) are there and the IM itself has no restrictions on foreign namespaces of course.
I have only one concern about the subproject at [queries-using-sparql](https://github.com/International-Data-Spaces-Association/InformationModel/tree/develop/examples/queries-using-sparql/SparqlQueries/). Can we move the java project to a side repo? Source code might be better placed separately. I know I have added some bash scripts myself, something I actually don't like much either...

**Comment by JohannesLipp** [comment]
Agree with that. Regarding the side repo: We currently have three exemplary implementations in the [our repo's example directory](https://github.com/International-Data-Spaces-Association/InformationModel/tree/develop/examples). This decision would include to move all examples to a side repo, or one in a dedicated repo each. 
Of course, it would clean up the repo, but a drawback is that people would need to search trough other repos for examples.

**Comment by HaydarAk** [comment]
New issue regarding the examples related discussion.

#275

**Comment by clange** [comment]
@sebbader @changqin26 
@JohannesLipp @HaydarAk 
I think the Java code generator has for a  long time been able to handle non-IDS namespaces. Therefore, this problem has been solved, hasn't it, and the issue can be closed – right?

**Comment by changqin26** [comment]
Yes, the basic functionality works for more than IDS.
