### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by dileep-rkm** [International-Data-Spaces-Association/InformationModel#191]
some examples such as https://github.com/IndustrialDataSpace/InformationModel/blob/examples/examples/DATA1.ttl needs to be updated and also remaining examples in the examples folder.
@HaydarAk 

Concrete issues include:
- outdated namespaces such as `idsc_content:`

**Comment by HaydarAk** [comment]
you're right. Thanks for the hint.

I'll update them soon :)

**Comment by clange** [comment]
Concrete issues include:
- outdated namespaces such as `idsc_content:`

**Comment by HaydarAk** [comment]
We have brand new examples in our `examples/` subdirectory. 

Was done in #323
