### ISSUE TITLE
Clarifiy which GitHub organization should be used in the future

### ISSUE THREAD

**Issue by np00** [International-Data-Spaces-Association/InformationModel#22]

**Comment by np00** [comment]
Currently, it is a bit confusing that the IDS uses two _GitHub organization_ accounts: 

https://github.com/IndustrialDataSpace
https://github.com/InternationalDataSpaces

I created them myself, but I am in no position to force anyone to move. The best way would probably to move everything & keep ReadMe's to point to the other place. Merging _GitHub Organizations_ seems to be not possible. 

it is also a not optimal that two repos exist for the same thing, which seems to be both actively used? 

https://github.com/IndustrialDataSpace/InformationModel
https://github.com/InternationalDataSpaces/InformationModel

**Comment by jpullmann** [comment]
Hi Niklas, 
neither of these accounts is officially mandated by [IDSA](http://internationaldataspaces.org/):
- https://github.com/IndustrialDataSpace
- https://github.com/industrial-data-space
- https://github.com/InternationalDataSpaces

Longer while ago we asked IDSA to set up an official account and consolidate the development activities. I'll forward your request accordingly. Please refer to [this Information Model repo](https://github.com/IndustrialDataSpace/InformationModel) as reference in meantime.
 Cheers
Jaro

**Comment by np00** [comment]
https://github.com/IndustrialDataSpace and https://github.com/InternationalDataSpaces were created by me, to save those. https://github.com/industrial-data-space by AISEC, correct? 

I assume as long as the developing Fraunhofer institutes agree on a single account, the IDSA will be happy to officially recommend it. 

+1 from my side for: https://github.com/InternationalDataSpaces

Thanks for pointing me to the active repo of the Information Model!

**Comment by sebbader** [comment]
I guess we can close this ticket, right @np00 ? Not much we can do about it here.

**Comment by HaydarAk** [comment]
Done.
See #229 and #253
