### ISSUE TITLE
Specify what attributes are required for what message classes

### ISSUE THREAD

**Issue by clange** [International-Data-Spaces-Association/InformationModel#221]
Input from Plugfest: are all properties in the upper section of http://htmlpreview.github.io/?https://github.com/IndustrialDataSpace/InformationModel/blob/feature/message_taxonomy_description/model/communication/Message_Description.htm supported by all message types listed in the lower part? If not, then make explicit in the lower table what attributes are required for what message classes.

**Comment by HaydarAk** [comment]
Done.  

Edited the description texts of https://w3id.org/idsa/ids-messages and added that:
- all messages in the second table support all properties of the core ids:Message. 
- added a column in the second table for list of properties of the core ids:Message, which were optional for the core class but mandatory for the specific message. E.g., correlationMessage Property for all ResponseMessages.
