### ISSUE TITLE
Transfer repository to IDSA organization

### ISSUE THREAD

**Issue by HaydarAk** [International-Data-Spaces-Association/InformationModel#229]
1. DONE Find out what information could be lost in a repository transfer
2. DONE Get access / write permissions in the [IDSA organization](https://github.com/International-Data-Spaces-Association/)
3. Move repository
4. Edit links pointing to this repository
5. Tell the world about it
6. Rebuild the old README which explains the move. 
 
**Comment**: Not sure in what state the old repository will be after the transfer. Since all incoming links are already redirected, maybe redirecting links is not even needed. "_All links to the previous repository location are automatically redirected to the new location._" ([Source](https://help.github.com/en/github/administering-a-repository/transferring-a-repository))

Links to **GitHub Pages** are not redirected. Who owns https://w3id.org/idsa/core? Is it @sebbader ? This currently redirects to a https://industrialdataspace.github.io/InformationModel/docs/index.html and thus will have to be fixed.

[Useful link: Transfer issues](https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository)

**Comment by clange** [comment]
Hmm, can't edit this issue any more, now that it has been moved to the new organization. Anyway, we are at Step 4. All active developers should apply `git remote set-url origin 'https://github.com/International-Data-Spaces-Association/InformationModel'` to their clone.

**Comment by clange** [comment]
We are mostly done with this. @HaydarAk I'm just wondering about point (6) above "rebuild the old README which explains the move". I no longer understand what this means…

**Comment by sebbader** [comment]
can we close this now? I am pretty happy with the applied actions :-)

**Comment by JohannesLipp** [comment]
Thank you!
The last puzzle piece IMHO is the updated references. I linked that pull request, which should be sufficient to close this issue.
