### ISSUE TITLE
dataTransfer/receiver and others declared both as DatatypeProperty and ObjectProperty

### ISSUE THREAD

**Issue by clange** [International-Data-Spaces-Association/InformationModel#23]
There is a bug in the ontology at http://ids.semantic-interoperability.org/ (I have no idea what source in this repository this corresponds to): Protégé complains dataTransfer/receiver and others are declared both as DatatypeProperty and ObjectProperty, which is not allowed even with punning.

**Comment by HaydarAk** [comment]
Properties are not even part of the IM anymore :) 
Therefore, this can be closed.
