### ISSUE TITLE
DatPayload requires Attributes 

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/InformationModel#232]
- SecurityProfile
- extendedGuarantee
...

**Comment by sebbader** [comment]
See also Communication Guide specification to DAT and DAT Request

**Comment by sebbader** [comment]
see `feature/datPayloadAttributes` branch.

**Comment by sebbader** [comment]
I need to test these changes more, and need to verify that the updates work with the upstream tool chain.

**Comment by HaydarAk** [comment]
Fixed in #239
