### ISSUE TITLE
ids_da:version is incompatible with dct:hasVersion

### ISSUE THREAD

**Issue by VladimirAlexiev** [International-Data-Spaces-Association/InformationModel#25]
https://github.com/IndustrialDataSpace/InformationModel/blob/develop/modules/dataAsset/DataAsset.ttl#L49
```ttl
ids_da:version rdfs:subPropertyOf dct:hasVersion;
  rdfs:range xsd:string;
  rdfs:comment "Version identifier of the InfrastructureComponent."@en.
```

Many people make the mistake that `dct:hasVersion` is some sort of version number. It is not:
```ttl
dct:hasVersion
    rdfs:comment "A related resource that is a version, edition, or adaptation of the described resource."@en ;
    rdfs:subPropertyOf dc:relation, dct:relation ;
```
In fact it's inverse of `dct:isVersionOf` (even though not declared in dct).

So, remove that `rdfs:subPropertyOf`.

**Comment by HaydarAk** [comment]
interesting idea. Never thought about having version numbers for infrastructure components like Connector and Broker. 
Currently, components are solely identified by its IM compatibility. 
@sebbader  any opinion regarding this?

**Comment by sebbader** [comment]
I'd like to keep the view: The latest version of the IM contains the "truth" (to the best of our knowledge...). Means, old stuff is by definition outdated and risky. Therefore, I share your opinion, @HaydarAk, and would strongly discourage us to put versions to the entities declared in the IM itself.

However, what we need is a mechanism saying:
This Resource is the fourth one of its kind.

Any ideas on that? Maybe @JohannesLipp, as you know way more about DCAT properties?

**Comment by JohannesLipp** [comment]
@VladimirAlexiev is right: The `dct:hasVersion` property is intended to be used to link a general described resource to one of its versions. See https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/hasVersion and http://udfr.org/docs/onto/dct_hasVersion.html

We use `ids:version` to link a `ids:ManagedEntity` to its version identifier, instead of a version/implementation/instance - and therefore, the `ids:version rdfs:subPropertyOf dct:hasVersion;` is misleading indeed.

Do we instead have a proper property that we can extend?

**Comment by clange** [comment]
Re. `dct:hasVersion` I just had a look into [what DCAT recommends](https://www.w3.org/TR/vocab-dcat-2/#dataset-versions), and in fact it doesn't recommend much. Re. version numbers/identifiers I don't know. For data resources we might (ab)use `owl:versionInfo` (some of you may recall the related discussion we had in our internal Fraunhofer Digital project). For software I'm sure there also exist ontologies. Other than querying LOV, there is nothing that immediately comes to my mind, in any case not a domain-independent property.

**Comment by VladimirAlexiev** [comment]
@clange dct:version says enough to see that it is not a version number.

The commonly used ontology for describing software projects is DOAP

**Comment by lcomet** [comment]
Checking this thread and the model, there is no such a ids_da:version anymore in our model, only a dct:hasVersion which is the only property in use for referring to versions, after the refactoring done in #413  and PR #504
