### ISSUE TITLE
Transport Certs SHA256 in Self Description

### ISSUE THREAD

**Issue by maboeckmann** [International-Data-Spaces-Association/InformationModel#256]
Currently, the transport certificate SHA256 hash can be attached to the self-description of connectors, as well as to the DAT payload, see [here](https://github.com/International-Data-Spaces-Association/InformationModel/blob/develop/model/infrastructure/Connector.ttl#L103).
Is there any point in having the certificate hash somewhere outside of the DAT? This information could not be trusted anyways. Hence it might just be "data garbage". From my understanding, having the certificate hash as part of the DAT is both required and sufficient.

**Comment by maboeckmann** [comment]
How fitting that this issue is numbered 256 ! ;)

**Comment by sebbader** [comment]
I am pretty sure you have waited a long time to open this one!

**Comment by sebbader** [comment]
Has been solved with the referenced PR.
