### ISSUE TITLE
Align information from IDS-G and Information Model 

### ISSUE THREAD

**Issue by HaydarAk** [International-Data-Spaces-Association/InformationModel#267]
Check / compare the information provided in the draft branch of the [IDS-G repository](https://github.com/International-Data-Spaces-Association/IDS-G/tree/draft/) with the contents of the Information Model. 

E.g. check if one source is missing information that the other source already contains such as properties of core classes, DAPS token representation and so on.

**Comment by JohannesLipp** [comment]
This is nowadays automatically covered during our "new version checklist", cf. https://github.com/International-Data-Spaces-Association/InformationModel/blob/develop/.github/PULL_REQUEST_TEMPLATES/PULL_REQUEST_TEMPLATE.md
