### ISSUE TITLE
Message table documentation @ IDS-G

### ISSUE THREAD

**Issue by HaydarAk** [International-Data-Spaces-Association/InformationModel#268]
The documentation of the message taxonomy (https://w3id.org/idsa/ids-messages) should be transfered to a document (e.g. markdown doc) in the IDS-G repository if possible.   

Currently, the documentation is based on an Excel spreadsheet:
- which is maintained and updated manually 
- exported to HTML 
- pushed to a [specific branch](https://github.com/International-Data-Spaces-Association/InformationModel/tree/feature/message_taxonomy_description) in this repository
- can be viewed using the persisted w3id url and the [github htmlpreview](https://htmlpreview.github.io/) feature. 

Switching to an e.g. markdown document would allow an easier maintanace process and automated updates in the future.

**Comment by JohannesLipp** [comment]
Closed due to inactivity. Please comment & reopen, if still relevant. Thank you!
