### ISSUE TITLE
language, temporal, spatial

### ISSUE THREAD

**Issue by VladimirAlexiev** [International-Data-Spaces-Association/InformationModel#27]
You define language, temporal and spatial as sub-props of DCT, but I can't see how are the respective classes richer than DCT. Why not use DCT directly?

Eg here's a discrepancy:
```ttl
ids_da:coversLanguage rdfs:subPropertyOf dct:language;
    rdfs:range ids_lang:Language;
    rdfs:comment "States the language that is used in the DataAsset."@en.
```
On the other hand, 
```ttl
dct:language rdfs:range dct:LinguisticSystem ;
```
By RDFS reasoning from DCT and IDS_DA, every object of `ids_da:coversLanguage` will get type `dct:LinguisticSystem`. But there's no connection between `ids_lang:Language` and `dct:LinguisticSystem` declared by IDS, so only the *used* languages will get this type. Is this really intended?

(BTW, I think the name `ids_da:coversLanguage` is not very accurate. A dictionary covers a language; a resource that merely uses a language cannot be said to **cover** it.)

Cheers!

**Comment by sebbader** [comment]
The reason for not directly using the original entities was that our generated tools and libraries required the IDS namespace. This has been solved by now, so we will not need to apply this kind of namespace hijacking anymore.
