### ISSUE TITLE
Values of "DatPayload/scope" need to be defined

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/InformationModel#271]
For instance, several examples mention the "scope":"ids_connector_attributes" but it's not part of the IM.

**Comment by gbrost** [comment]
Lets call it idsc:IDS_CONNECTOR_ATTRIBUTES and make upper case the default, ok?

**Comment by sebbader** [comment]
PullRequest is on the way. When you need more, please just continue to open tickets like this and we will insert them. (maybe faster next time).
