### ISSUE TITLE
Repository for (code) examples

### ISSUE THREAD

**Issue by HaydarAk** [International-Data-Spaces-Association/InformationModel#275]
Derived from the issue #190

---

>I have only one concern about the subproject at queries-using-sparql. Can we move the java project to a side repo? Source code might be better placed separately. I know I have added some bash scripts myself, something I actually don't like much either...
[...]
Agree with that. Regarding the side repo: We currently have three exemplary implementations in the our repo's example directory. This decision would include to move all examples to a side repo, or one in a dedicated repo each.
Of course, it would clean up the repo, but a drawback is that people would need to search trough other repos for examples.

I would suggest to move all examples into one side-repository and use sub-folders for the different examples. Even though our code examples are complete and more or less standalone, it might be confusing to have separate repositories for every little bit of code. 

Later on, we should check and update references to these examples.

**Comment by sebbader** [comment]
I think this has been solved by the PR #298 . I close the issue.
