### ISSUE TITLE
ParIS is subClass of?

### ISSUE THREAD

**Issue by jlangkau** [International-Data-Spaces-Association/InformationModel#284]
ParIS is currently subClass of ids:Connector. Is it not a subClass of Broker (aka. MetaDataBroker, MDB)?

**Comment by sebbader** [comment]
Hi @jlangkau !
Thank you for your proposal. Even though the Broker and ParIS are certainly very similar in their scope - and using the same code base in our implementation - a subClass relation is a bit too much I think.
That would mean that *every* ParIS is *always* a complete Metadata Broker, with all it's features and requirements. I don't see this, to be honest.

What's you opinion here?

regards,
Sebastian

**Comment by jlangkau** [comment]
Hey @sebbader!

Everything is fine! I get it some time ago, that ParIS get all features from MDB - and some on top... So I'm fine, if ParIS is a "normal" connector...

j.

**Comment by sebbader** [comment]
ok, then let me close this ticket. Still, please continue asking questions like this also as issues here! This gives us a better impression on bugs/missing features and let's us track the processes way easier.
