### ISSUE TITLE
Message metadata

### ISSUE THREAD

**Issue by mkollenstart** [International-Data-Spaces-Association/InformationModel#285]
`Message`s currently do not support the addition of metadata belonging to the message at this moment.

For instance, when we do want to create a `InvokeOperationMessage` with a specific payload (e.g. the contents of a file) and metadata (e.g. specific parameters so that the receiver can handle the file) a custom serialization of both the payload and metadata is created that wraps both in the form of a JSON message.
However, when the size payload becomes large wrapping the payload with the metadata becomes a problem as the full file must be read in advance. 
If we can embed the metadata inside the `RequestMessage` itself we can use streaming approaches to send and handle the payload itself.

For our usecase, the ideal scenario would be to have a map-like element in the `Message` class that we can use for additional metadata.

**Comment by sebbader** [comment]
Hello @mkollenstart !

I think you have a really relevant use case here. I would see it even more general, for instance for streaming data:
I want to send the metadata beforehand, and then exchange the payload content in the following interactions. That is certainly not possible (or thought through?) at the moment. Maybe we can come up with some ideas during the plugfest this week?

Best,
Sebastian

**Comment by mkollenstart** [comment]
Thanks, Sebastian, for the reply.

Indeed, the more general case of streaming data is also a very interesting case. But that would be primarily for the communication through IDSCP, where sending the metadata in front of the actual data would be a very good idea.

However, for the HTTP multipart communication this approach will probably not work be the best idea, as a single request would be more logical for this. My current ideas are either using additional parts in the HTTP multipart or having a more free-format for the IDS Message as suggested above.

But indeed, lets discuss this during the plugfest.

**Comment by JohannesLipp** [comment]
Closed due to inactivity.
@mkollenstart please simply reopen (and comment recent updates) if this is still relevant, thank you! Please note that we will have  focus sessions on the IDS Infomodel during the next IDS Plugfest sessions. Please feel free to contribute a spotlight on interesting topics (e.g., like this one, if it is still relevant).
