### ISSUE TITLE
More Broker information

### ISSUE THREAD

**Issue by steffenbiehs** [International-Data-Spaces-Association/InformationModel#290]
The InformationModel should persist more information about the Broker, e.g. at which Broker the IDS-Connector is registered. And of course should this value be empty if the IDS-Connector isn't registered at any Broker.

**Comment by HaydarAk** [comment]
I'm not sure, if this information should be part of a Connectors self-description. 
The Broker is the index for Connectors and Resources in the IDS. That is whole idea behind the Broker. 

Usually a Connector (or user) in the IDS communicates either to:
- the Broker, to ask for Connectors / Resources.
- a Connector directly (which it already knows) to start some kind of data / metadata exchange process. 

If we add something like "Connector X is registered at Broker Y" to a Connector and its self-description, what do we gain from this information ? 
Why would a Connector A want this information from a Connector B?  To get back to the Broker? Makes no sense to me.

**Comment by jlangkau** [comment]
Hello Haydar!
Your thoughts are valid. But: one idea, why it (maybe) makes sense. MDB is an optional component of given eco-system. I think that a given MDB could be some kind of honeypot for connectors with a special flavour (service/data provided) and wants to show to be in good companion and competition to those?!?

**Comment by sebbader** [comment]
Hello Jörg! 
I'd say this use case is not directly necessary to enable the operation in a general IDS ecosystem. I, therefore, would like to assign it a rather low priority and focus on the crucial features first.
Best,
Sebastian

**Comment by JohannesLipp** [comment]
Closed due to inactivity. Please comment & reopen, if still relevant. Thank you!
