### ISSUE TITLE
Refinment of Obligations

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/InformationModel#291]
Obligations can be intended to be evaluated before (Pre-Usage Obligations), at (Ongoing-Usage Obligations), or after (Post-Usage Obligations) the usage event. The IDS Obligation class must represent this fact by either:
* becoming abstract with three new subclasses (preferred) 
* a new attribute explaining the intended execution time

**Comment by sebbader** [comment]
Just thinking loud: What are `Ongoing-Usage Obligations`? No clue how to tell an enforcement engine to do two things at the same time. I'd rather skip them, and stay with pre- and post-obligations.

**Comment by HaydarAk** [comment]
Regarding your modeling ideas for obligations:
I also prefer the first idea over the second.

>Just thinking loud: What are Ongoing-Usage Obligations?
My initial understading was: "While doing the agreed action X, you have to ensure >".
In another domain, lets say chemistry, I'd say ongoing ogligations are something like _While working with chemical X, you have ensure Y, e.g. that everyone wears gloves_

Currently, I cant imagine a realistic ongoing obligation. But this means nothing :)

**Comment by jlangkau** [comment]
@sebbader : is

> While working with

(ongoing, until work is done) an event? Oh, there it is again, my good ol' friend „accident“ I spend a lot of time with... „accident“: when is this status NOT ongoing any longer, so something is NOT in this context, so we aren't allowed to read geolocation of given car?

**Comment by JohannesLipp** [comment]
Closed due to inactivity.
@hosseinzadeha if that topic is still relevant, please simply reopen this issue and comment further tasks, thank you!
