### ISSUE TITLE
Remove non-used Classes and Properties

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/InformationModel#293]
Several classes, properties, taxonomies and instances in the current version have never been used, and no realistic use case is currently presented. I suggest to list such entities, and delete them from the model. This shall reduce the overall complexity of the model and help the users to find what is really relevant.

I have prepared suggestions in the branch feature/simplifications already.

**Comment by sebbader** [comment]
https://github.com/International-Data-Spaces-Association/InformationModel/tree/feature/simplifications

**Comment by sebbader** [comment]
Furthermore, I want to remove Operations from the model. It is not in the core focus of the IDS, and only provides minimal added value while at the same time presenting a huge set of classes and relations.

**Comment by sebbader** [comment]
And I want to get your opinion on our Licenses. This enumeration is, and always will be, incomplete. I strongly suggest using a third party vocabulary instead of trying our own model.

**Comment by jlangkau** [comment]
> Furthermore, I want to remove Operations from the model. It is not in the core focus of the IDS, and only provides minimal added value while at the same time presenting a huge set of classes and relations.

A very good move!

**Comment by jlangkau** [comment]
> Several classes, properties, taxonomies and instances in the current version have been never used, and no realistic use case is currently presented. I suggest to list such entities, and delete them from the model. This shall reduce the overall complexity of the model and help the users to find what is really relevant.
> 
> I have prepared suggestions in the branch feature/simplifications already.

This is a very good idea - but: are you shure, that know one (out in the field) is using some of those you want to eleminate?

**Comment by HaydarAk** [comment]
I agree with Sebastian. 👍  But removing Operations inevitably leads to a re-design of (interactive) endpoints, since interactive endpoints are mainly based of the operations as far as I knmow.

>This is a very good idea - but: are you shure, that know one (out in the field) is using some of those you want to eleminate

Good question

---

I'd like to add the `Activities` to the list of things that we should remove.

**Comment by clange** [comment]
> 
> 
> And I want to get your opinion on our Licenses. This enumeration is, and always will be, incomplete. I strongly suggest using a third party vocabulary instead of trying our own model.

I fully agree – could someone try to find one? I'm not so sure that there _is_ such a thing. However, being incomplete should be OK, because the IDS infomodel already has a way of referring to "non-standard" licenses.

**Comment by HaydarAk** [comment]
`model/contract/PricingModel.ttl`
`model/contract/Payment.ttl`

In my understanding, these classes are outdated and are now part of the usage policy.
Remove them, @sebbader ? 🗑️

**Comment by sebbader** [comment]
90% sure that you are right, @HaydarAk. I think those were left overs from some business-related discussions, which we have never finished in any appropriate manner... But yes, the input from the IDSA Legal WG puts these ideas into the contracts.
