### ISSUE TITLE
Switch from ids:License Enum to Wikidata License Instances

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/InformationModel#296]
IDS should and cannot maintain a complete License Vocabulary. We need to validate whether the Wikidata entities are suited for our purposes.

Issues:
* Wikidata uses own properties, not the commonly known rdf/rdfs ones
* Wikidata identifiers are codes instead of human-friendly and readable ones
* Using sameAs relations will import a lot of additional, probably not necessary Wikidata annotations.

**Comment by sebbader** [comment]
Related to #293

**Comment by clange** [comment]
[This query to Wikidata](https://query.wikidata.org/#SELECT%20%2a%20WHERE%20%7B%20%7B%20%3Fs%20p%3AP31%2Fps%3AP31%2Fp%3AP31%2Fps%3AP31%20wd%3AQ79719%20%7D%20UNION%20%7B%20%3Fs%20p%3AP31%2Fps%3AP31%2Fp%3AP31%2Fps%3AP31%20wd%3AQ79719%20%7D%20.%20%3Fs%20rdfs%3Alabel%20%3Fl%20.%20FILTER%20%28langMatches%28lang%28%3Fl%29%2C%22en%22%29%29%20%7D) is promising. While, however, at a first glance it seems to me that "license" (Q79719) is the only applicable superclass, this is clearly too wide, as it also comprises stuff like "driving license". On the other hand, e.g., CC0 is mis-classified as a "software license" and "data" or "content license" does not exist.

**Comment by HaydarAk** [comment]
Some additional information:
Licenses at wikidata (should) have a property called [full work available at URL](https://www.wikidata.org/wiki/Property:P953) which point to the license source. 
There further indicates that wikidata is a suitable source for us. :)
