### ISSUE TITLE
Submit Information Model to LOV

### ISSUE THREAD

**Issue by HaydarAk** [International-Data-Spaces-Association/InformationModel#302]
Submit Information Model to [Linked Open Vocabularies](https://lov.linkeddata.es/dataset/lov/) :)

**Comment by JohannesLipp** [comment]
The submission failed due to an internal server error with the LOV website, a Java ClassCastException to be precise.

I contacted the responsible people via email and will update this issue once we get a reply.

**Comment by JohannesLipp** [comment]
Update: We do not meet the requirements given by LOV, see the report below. 

In short: Adding N3 serialization might be sufficient to join LOV. @sebbader @HaydarAk Who can add this to our Widoco pipeline, and re-run it?


![image](https://user-images.githubusercontent.com/15930331/93187894-99e34f00-f740-11ea-80d3-4ac68565d030.png)
[Link I used to create that report](http://linkeddata.uriburner.com:8000/vapour?uri=https%3A%2F%2Fw3id.org%2Fidsa%2Fcore&acceptRdfXml=1&acceptTurtle=1&acceptN3=1&acceptRdfJson=1&acceptJsonLD=1&htmlVersions=1&defaultResponse=dontmind&userAgent=http%3A%2F%2Flinkeddata.uriburner.com%3A8000%2Fvapour%23this)

**Comment by JohannesLipp** [comment]
![image](https://user-images.githubusercontent.com/15930331/93476920-a01d2b00-f8fa-11ea-8ed7-bdc138f4bd16.png)

**Comment by sebbader** [comment]
Hi @JohannesLipp, the N3 support is now also in the redirects file: https://github.com/sebbader/w3id.org/pull/2 
@HaydarAk and @JohannesLipp please review my changes, let me know if and where I screwed up stuff, and then I am confident to create the PR to w3id.

**Comment by sebbader** [comment]
Please also review and merge #366 when finished with this topic.

**Comment by JohannesLipp** [comment]
It is not trivial to review the changes properly. I did a code inspection, and the updates look good to me. A proper check can IMHO only be done by merging that branch an re-run the external check against our update live version.

**Comment by JohannesLipp** [comment]
Update: @sebbader updated our redirects, and submitted a PR to the w3id repo

**Comment by sebbader** [comment]
PR is merged. @JohannesLipp please run again the LOV checks.

**Comment by JohannesLipp** [comment]
Thank you. The Vapour report improved, especially for N3 serialization: 
![image](https://user-images.githubusercontent.com/15930331/94117644-c5ef8600-fe4c-11ea-8621-41d8f0f88fd2.png)


Since the LOV submission still fails, I asked the LOV team for feedback. I will get you tuned here.

**Comment by JohannesLipp** [comment]
Update/decision: @HaydarAk updates the redirects accordingly, and will notify you @sebbader to merge it to w3id.

**Comment by JohannesLipp** [comment]
Update: 
Thanks to @HaydarAk , the Vapour report is rated 3/3 in all categories now:
![image](https://user-images.githubusercontent.com/15930331/98908483-c9080980-24c0-11eb-9d25-146539a9bff6.png)

Unfortunately, the LOV submission still fails due to some ClassCastException. I again contacted the LOV team just now, asking for further guidance on the following error:

```
java.lang.ClassCastException: com.hp.hpl.jena.datatypes.BaseDatatype$TypedValue cannot be cast to com.hp.hpl.jena.datatypes.xsd.XSDDateTime at com.hp.hpl.jena.sparql.expr.NodeValue._setByValue(NodeValue.java:1118) at com.hp.hpl.jena.sparql.expr.NodeValue.nodeToNodeValue(NodeValue.java:1027) at com.hp.hpl.jena.sparql.expr.NodeValue.makeNode(NodeValue.java:350) at com.hp.hpl.jena.sparql.expr.ExprVar.eval(ExprVar.java:65) at com.hp.hpl.jena.sparql.expr.ExprVar.eval(ExprVar.java:54) at com.hp.hpl.jena.sparql.expr.ExprNode.eval(ExprNode.java:77) at com.hp.hpl.jena.sparql.expr.ExprFunction1.eval(ExprFunction1.java:70) at com.hp.hpl.jena.sparql.expr.ExprNode.eval(ExprNode.java:77) at com.hp.hpl.jena.sparql.expr.ExprFunctionN.eval(ExprFunctionN.java:109) at com.hp.hpl.jena.sparql.core.VarExprList.get(VarExprList.java:82) at com.hp.hpl.jena.sparql.engine.iterator.QueryIterAssign.accept(QueryIterAssign.java:68) at com.hp.hpl.jena.sparql.engine.iterator.QueryIterProcessBinding.hasNextBinding(QueryIterProcessBinding.java:64) at com.hp.hpl.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:112) at com.hp.hpl.jena.sparql.engine.iterator.QueryIterProcessBinding.hasNextBinding(QueryIterProcessBinding.java:60) at com.hp.hpl.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:112) at com.hp.hpl.jena.sparql.engine.iterator.QueryIterProcessBinding.hasNextBinding(QueryIterProcessBinding.java:60) at com.hp.hpl.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:112) at com.hp.hpl.jena.sparql.engine.iterator.QueryIterConvert.hasNextBinding(QueryIterConvert.java:59) at com.hp.hpl.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:112) at com.hp.hpl.jena.sparql.engine.iterator.QueryIterDistinctReduced.hasNextBinding(QueryIterDistinctReduced.java:54) at com.hp.hpl.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:112) at com.hp.hpl.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:40) at com.hp.hpl.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:112) at com.hp.hpl.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:40) at com.hp.hpl.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:112) at com.hp.hpl.jena.sparql.engine.ResultSetStream.hasNext(ResultSetStream.java:75) at org.lov.SPARQLRunner.getLiterals(SPARQLRunner.java:83) at org.lov.LovBotVocabAnalyser.analyse(LovBotVocabAnalyser.java:128) at org.lov.LovBotVocabAnalyser.analyseVocabURI(LovBotVocabAnalyser.java:48) at org.lov.cli.Suggest.exec(Suggest.java:71) at arq.cmdline.CmdMain.mainMethod(CmdMain.java:101) at arq.cmdline.CmdMain.mainRun(CmdMain.java:63) at arq.cmdline.CmdMain.mainRun(CmdMain.java:50) at org.lov.cli.Suggest.main(Suggest.java:27)
```

**Comment by JohannesLipp** [comment]
FYI just pushed that email once more, as there was no response yet.

**Comment by JohannesLipp** [comment]
We are live on LOV now! 
https://lov.linkeddata.es/dataset/lov/vocabs/ids

Please note that some fields will be automatically added after some automatic indexing tasks in the LOV backend.

**Comment by JohannesLipp** [comment]
Update: The indexing succeeded and all IDS terms can now be found via LOV, e.g., https://lov.linkeddata.es/dataset/lov/terms?q=Broker
