### ISSUE TITLE
Move source of message table to Teams

### ISSUE THREAD

**Issue by clange** [International-Data-Spaces-Association/InformationModel#317]
For easier maintenance of the editable source of the [message table](https://w3id.org/idsa/ids-messages), it would make sense to move it to Microsoft Teams (somewhere in the IDSA's agiplan organization). And then see how much of it we can get into IDS-G in coordination with @jlangkau.

**Comment by HaydarAk** [comment]
Is the IDSA Jive not better suited for this?

**Comment by JohannesLipp** [comment]
Closed due to inactivity. Please comment & reopen, if still relevant. Thank you!
