### ISSUE TITLE
IDS-PIP

### ISSUE THREAD

**Issue by jlangkau** [International-Data-Spaces-Association/InformationModel#328]
Regarding the fact a Policy Information Point is heavily used by given contract-templates ( Usage Control Object) we need to define (or make a recommandation) fpr a PIP-architecture that drives IDS-eco-system.

Document in JIVE is already up and running (https://industrialdataspace.jiveon.com/docs/DOC-3191), but I suggest to „discuss“, shape and brin it up in IDSG-pre on it's way to be a up-and-running industry standard:

https://github.com/International-Data-Spaces-Association/IDS-G-pre/tree/master/ids-pip

**Comment by sebbader** [comment]
Suggestion: Let's hijack a channel in the plugfest, get some interested guys and girls together, and directly note the results in the IDS-G-pre or https://industrialdataspace.jiveon.com/docs/DOC-3191. I will then model the results and put it for discussion in this thread.

**Comment by JohannesLipp** [comment]
@jlangkau is this still up-to-date? We now have a [discussion forum](https://github.com/International-Data-Spaces-Association/InformationModel/discussions) in our GitHub repo for such purposes. Maybe this was already solved by above-mentioned Plugfest collaborations. Thank you in advance.

**Comment by JohannesLipp** [comment]
Closed due to inactivity. Please reopen & comment, if this is still relevant. Thank you!
