### ISSUE TITLE
rightOperand and two ways to call a remote reference

### ISSUE THREAD

**Issue by jlangkau** [International-Data-Spaces-Association/InformationModel#329]
What is the difference (mechanic, NOT content) between 

ids:rightOperandReference ?notificationEndpointUrl ; # Send notification information to this URL

and

ids:rightOperand "true"^^xsd:boolean ;        # for a certain usage ?duration
ids:pipEndpoint ?askIfEventPipUri ;           # The PIP call for this event, for instance https//pip.com/path/isFIFA_World_Cup_tournaments or https//pip.com/ids?event=FIFA_World_Cup_tournaments

**Comment by JohannesLipp** [comment]
@jlangkau is this still up-to-date or did you solve that issue in the meantime? Thank you in advance!

**Comment by sebbader** [comment]
This one is outdated, yes, and can be closed.
