### ISSUE TITLE
Extend RejectionReason codes

### ISSUE THREAD

**Issue by cmader** [International-Data-Spaces-Association/InformationModel#38]
Extend value space for RejectionReason. Review related work (e.g., HTTP error status codes) and check if they can be reused.

**Comment by sebbader** [comment]
#e2e7158d12f738cf1f301b7ff856c2addc9b1624

**Comment by HaydarAk** [comment]
@sebbader
Need more codes?

**Comment by JohannesLipp** [comment]
There are 11 in `RejectionReason.ttl` and we currently have no requirements for more, so closing this.
