### ISSUE TITLE
Create and follow check list for future releases

### ISSUE THREAD

**Issue by clange** [International-Data-Spaces-Association/InformationModel#381]
For any future release, the following steps should be followed. First of all, these steps should be documented in a central place, and then we should copy them as a check list to an issue or to the pull request for merging the changes for the new revision into the master branch. Please edit this issue's description to make it complete.

1. provide complete validation shapes for the new ontology terms; remove shapes for the old ones
1. create upgrade shapes from the previous revision to the new one
1. update and validate, against the shapes, the examples to use the latest ontology version
1. generate human-readable documentation and single-file serializations using Widoco
1. make sure that the manually authored parts of the documentation (including the human-readable description of the examples) are in sync with the rest of the implementation and documentation
1. update [the message table](https://w3id.org/idsa/ids-messages)
1. generate Java library
1. update changelog

**Comment by JohannesLipp** [comment]
Note that the first bullet might be solved/supported by !147

**Comment by JohannesLipp** [comment]
4. Is triggered manually currently, and the output must be pushed to the `gh-pages` branch for automatic synchronization.

**Comment by JohannesLipp** [comment]
One addition to point 8: Inform Plugfest member about new features in time, so that they can be discussed before publishing.

**Comment by HaydarAk** [comment]
Addition: Add template for pull requests which can be used as part of the release management

**Comment by JohannesLipp** [comment]
Solved
