### ISSUE TITLE
Setup an FAQ "How to use the Infomodel"

### ISSUE THREAD

**Issue by JohannesLipp** [International-Data-Spaces-Association/InformationModel#385]
The developers (users) of the IDS Infomodel ask for more documentation on real-world / practice applications. Instead of writing more comprehensive documents on Jive etc., a handy FAQ would be much more helpful.

Please setup an FAQ document, where users (e.g., from the PlugFest) contribute the questions, and the IDS Infomodel team provides practical answers to these.

**Comment by changqin26** [comment]
I have created an FAQ for Infomodel.md file under my branch: changqin. Can you check if it is the one you expect?

**Comment by JohannesLipp** [comment]
Thanks @changqin26 ! Could you please create a pull request (PR) for that, link it to this issue, and set me as "reviewer" for that PR? We are currently setting up a more "controlled" workflow, and thus ourselves should follow it strictly :P Thanks!

**Comment by changqin26** [comment]
Sorry I wrongly added this FAQ commit to my last pull request. please check the newest pull request #390.
