### ISSUE TITLE
Configmanager Routen boolean

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/InformationModel#387]
Hi @HaydarAk,

inside a appRoute we need a boolean to indicate that a route is broken, meaning that there is no route from Start A to End Z (because some subroutes a not connected).

Best regards,
Heinrich

**Comment by HaydarAk** [comment]
Hi @HeinrichPet 
I see the problem, but I am not sure that this kind of information belongs to the Information Model. Let me explain why I think it does not belong there:

In my opinion, it is a task of the "application logic" to ensure that a route is _complete_, before it is persisted.   _Complete_ = Start A and End Z are connnected via some subroutes.

I think we should have a clear distinction between our "persistance layer" (the Information Model) and our application layer. On the persistance layer, there are basic syntactic and semantic checks (does X contain all mandatory properties and is therefore valid) while runtime / application specific information has to be checked in the application layer. A broken app route is similar to a `Connector Self description message` which has no payload -> Both are incomplete / incorrect.

**Comment by HeinrichPet** [comment]
Hi @HaydarAk 

you are right. Then the issues can be closed.
