### ISSUE TITLE
Security Token support for Message class

### ISSUE THREAD

**Issue by cmader** [International-Data-Spaces-Association/InformationModel#39]
According to the envisioned IDS secure communication scenario, there are 2 different security tokens involved: 
(1) an identity token that is retrieved from the identity provider in the connector onboard phase and presented in each subsequent infrastructure component interaction,
(2) an authorization token that can optionally be issued by a (data providing) connector to another (data consuming) connector in order to give different requesting connectors different access rights. Issuing authorization tokens may be done by proprietary components internal to the (data providing) connector.

As a consequence, I propose these changes:
(1) rename the authenticationToken property of the Message class to identityToken
(2) add a new property authorizationToken to the Message class
(3) rename the class AuthenticationToken to SecurityToken which will be the range of the properies in (1) and (2). It should hold general informaiton and the value of the token.

Does this sound ok?

**Comment by cmader** [comment]
in the current 1.0.2 version we have **ids:securityToken** for the DAPS token and **ids:authorizationToken**. There is a general ids:Token class which is the range of these two properties. Even though "securitytoken" probably is not the best name, I'd recommend to stick to it for now to retain compatibility with existing implementations and close this issue.

**Comment by cmader** [comment]
alternative names for "securityToken" could be "dapsToken" (the obvious choice), "dynamicAttributesToken" or "idsToken".

**Comment by sebbader** [comment]
The `ids:securityToken` is a stable and accepted property, therefore this issue has been solved with 1.0.2 already.
