### ISSUE TITLE
Investigate pros and cons of versioning in the ontology URI

### ISSUE THREAD

**Issue by JohannesLipp** [International-Data-Spaces-Association/InformationModel#394]
Research practices and related work, and decide whether we should include a version number (e.g., 2020-12-03) in the ontology URI. The base URI https://w3id.org/idsa/core would always be considered as latest and therefore redirect there. Other links allow direct access of later versions, too.

**Comment by JohannesLipp** [comment]
https://www.w3.org/TR/swbp-vocab-pub/#recipe4 looks promising. Applying this would mean the following for us:

**Before:**
- Just one (=most recent) [ontology.ttl file](https://international-data-spaces-association.github.io/InformationModel/docs/serializations/ontology.ttl)
- Just one (=most recent) documentation page at https://w3id.org/idsa/core
- Both being silently overwritten with new versions whenever we publish them

**After:**
![image](https://user-images.githubusercontent.com/15930331/102358340-b2693c80-3faf-11eb-8552-6a8caed37ec7.png)
- Multiple ontology files like `ontology-3.1.0.ttl`, `ontology-4.0.0.ttl` and `ontology-4.1.0.ttl`
- Multiple documentation pages like http://w3id.org/idsa/core-310, http://w3id.org/idsa/core-400 and http://w3id.org/idsa/core-410
- Users can access any of these documentation pages via its URL, while the base URL always points to the most recent one.
- The ["old" ontology URL](https://international-data-spaces-association.github.io/InformationModel/docs/serializations/ontology.ttl) would stay, and always contain the most recent version.
- Users can access particular ontology versions via the particular documentation page, respectively.

For an example, see https://www.projekt-scope.de/ontologies/bpo/

**Comment by JohannesLipp** [comment]
@sebbader @maboeckmann @HaydarAk @changqin26 Could you please comment on my suggested approach? Core questions are: 

1. Are there any drawbacks with that approach?
2. Who can update our configuration to execute this?

**Comment by JohannesLipp** [comment]
You can use `prefix bpo: https://w3id.org/bpo/1-1#` and subsequently `ex:myInstance a bpo:Class` in your file. This would serialize to `https://w3id.org/bpo/1-1#Class`, exactly. You can later upgrade that prefix to, e.g., `prefix bpo: https://w3id.org/bpo/1-2`, but leave the rest unchanged - this would then use the newer version `https://w3id.org/bpo/1-2#Class`.

If you want to automatically use the newest version all the time, you would use `prefix bpo:https://w3id.org/bpo#` without any version identifier, because that one always redirects to the newest one.

**Comment by changqin26** [comment]
Understood, this versioning method is the same as that of the Asset Administration Shell.

**Comment by JohannesLipp** [comment]
Input from @clange : Follow https://www.debian.org/releases/ like so:
- stable = latest LTS (currently 4.0.0)
- testing = master branch
- unstable = develop branch

https://w3id.org/idsa/core should always point to the master branch, which is testing.
