### ISSUE TITLE
Key- & Truststore password in ConfigurationModel

### ISSUE THREAD

**Issue by ronjaquensel** [International-Data-Spaces-Association/InformationModel#398]
Hello @HaydarAk,

I'm currently working on creating camel routes from ConfigurationModel objects for the Configurationmanager. For this, I would need the passwords of the key- and truststore referenced there. Is it possible to add these fields to the ConfigurationModel?

**Comment by HaydarAk** [comment]
Hi! 

Adding a "password field" for both is easy. We can accomplish this by either 
- adding new fields to the ConfigModel class 

or
 
- expanding the truststore / keystore to full-fledged classes with their own (password) fields . 

Do you prefer one approach over the other ? 

---

**There is one thing, I would like to highlight:** 
I hope you are aware that adding this information to the Configuration Model may inevitably mean that the serialisation of the configuration model itself will be a security-critical information through the expose the passwords.

**Comment by ronjaquensel** [comment]
Hi,

thank you for the hint. We are aware of the security risk and are currently looking for a better solution, but for the time being this approach will suffice. 

Both of the suggested approaches would work for me.

**Comment by HaydarAk** [comment]
Done , see 5d0790e

The snapshot build of the java libs from our IAIS colleagues should soon (in the next few hours) contain these changes.
