### ISSUE TITLE
Fix issues with metamodel namespace

### ISSUE THREAD

**Issue by JohannesLipp** [International-Data-Spaces-Association/InformationModel#405]
"I see in the ontology triples like 
`<https://w3id.org/idsa/metamodel/competencyQuestion> rdfs:domain rdfs:Resource .`
Where do you define the metamodel ontology with this URI https://w3id.org/idsa/metamodel/ ?"

Please fix this, thanks. Since [the triples from the metamodel](https://github.com/International-Data-Spaces-Association/InformationModel/tree/develop/metamodel) are already included in the single-file IM, a quick win might be to redirect https://w3id.org/idsa/metamodel/ to that (i.e., version 4).

**Comment by HaydarAk** [comment]
Done since we removed the metamodel in our last version.
