### ISSUE TITLE
Dataspace Connector: "connect timed out"

### ISSUE THREAD

**Issue by FabioDangelox** [International-Data-Spaces-Association/InformationModel#411]
Currently i am trying to set up an example Dataspace. For this i am using two instances of the following Connector: https://github.com/FraunhoferISST/DataspaceConnector
Before i start the connectors i delete the proxy settings in the config.json on both of them.
After that i start one connector with the swagger ui on the port 8084 and the other one on port 8085.
In the next step i register a Resource on the Connector with the port 8085(Provider).
Additionally i add a Representation to the Resource.

Then i try on the Consumer(Port 8084) to retrieve the provided data:
I am also using the IP-Address and not localhost, as you can see in the picture:
![image](https://user-images.githubusercontent.com/78359600/106465745-ae7b7600-649a-11eb-98c9-24c0d72b4ddb.png)

And everytime i do this i get the follwing error messasge:

{
  "timestamp": "2021-02-01T13:12:45.300+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "connect timed out",
  "path": "/admin/api/request/description"
}

I dont know how to fix this issue.
It would be really nice if someone can help me here.

Thanks in advance.

Best regards,
Fabio D'Angelo

**Comment by HaydarAk** [comment]
Hi Fabio.
Please check my initial response in #412 regarding your issue. 

Best regards
Haydar Akyürek
