### ISSUE TITLE
Inconsistent Ontology

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/InformationModel#414]
Hi! Just tried the Pellet reasoner on the IDS IM. Unfortunately, this line https://github.com/International-Data-Spaces-Association/InformationModel/blob/218f952b6fad542fc786bb3cab1461c68fd5de46/metamodel/Annotation.ttl#L44 (`idsm:example [...]  rdfs:range rdf:PlainLiteral;`) results in an inconsistent model. Is there a good reason to keep it?

**Comment by JohannesLipp** [comment]
I personally do not require to keep this line. @HaydarAk what is your opinion on this?

**Comment by HaydarAk** [comment]
The IM evolved a bit over the last years and is now less dependent on the vocabulary of the `idsm` namespace.
For the next major version bump, we can compress the `idsm` vocabulary and therefore remove some properties we dont need anymore. The `idsm:example` could be part of that list. I dont see any particular reason to use `idsm:example` over `skos:example` or so if we want to document some kind of examples in the IM.

**Comment by sebbader** [comment]
👍 for the removal of the `idsm:` namespace. Replacing `idsm:example` with `skos:example` will not solve the error as long as the `rdfs:range rdf:PlainLiteral` statement stays. Can we delete that one nevertheless?

(By the way, I am still not sure why the rdf:PlainLiteral results in an inconsistent ontology. Most likely Pellet is not aware of some definitions. Isn't "<dateTimeStampLiteral>"^^xsd:dateTimeStamp a rdf:PlainLiteral ?)

**Comment by sebbader** [comment]
See #415

**Comment by sebbader** [comment]
Solved with #415
