### ISSUE TITLE
Attributes of an ids:Participant

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/InformationModel#416]
The current Participant class has the following attributes:

https://w3id.org/idsa/core/version | http://www.w3.org/2001/XMLSchema#string | Version identifier of the Managed Entity
-- | -- | --
  | https://w3id.org/idsa/core/corporateEmailAddress | http://www.w3.org/2001/XMLSchema#string | Email address for contacting the participant on a general level.
  | https://w3id.org/idsa/core/corporateHomepage | http://www.w3.org/2001/XMLSchema#anyURI | General official homepage of the participant.
  | https://w3id.org/idsa/core/memberParticipant | https://w3id.org/idsa/core/Participant | Indicates that a participant has a member which  is again a participant. This is useful for defining hierarchical  relations in a participant's organization as well as identifying groups  of participants to capture, e.g., members of a collaboration.
  | https://w3id.org/idsa/core/participantRefinement | https://w3id.org/idsa/core/AbstractConstraint | Conditions which needs to be satisfied that a  single Participant can be seen as a member of the subject Participant.  For instance, all Participants with their headquarter in Europe might be  a potential consumer of GDPR-releated data.
  | https://w3id.org/idsa/core/memberPerson | https://w3id.org/idsa/core/Person | Indicates membership of a person to an organization.
  | https://w3id.org/idsa/core/participantCertification | https://w3id.org/idsa/core/ParticipantCertification | Certification issued for the given Participant.
  | https://w3id.org/idsa/core/primarySite | https://w3id.org/idsa/core/Site | Indicates a primary site for the Organization,  this is the default means by which an Organization can be contacted and  is not necessarily the formal headquarters.

That's not so much. We need to add a few more critical things, for instance VAT, 'Handelsregistereintrag', 'Gerichtssitz', responsible manager, ...

**Comment by sebbader** [comment]
See here for an (not necessarily updated) state of the Participant: https://dydra.com/sebastianrbader/ids/@query#participant-attributes

**Comment by changqin26** [comment]
Why ids:industrialClassification, this property of ids:Participant is removed?

**Comment by JohannesLipp** [comment]
"We need to add a few more critical things": @sebbader could you please tell us what exactly you would like to add? Is there a list/table documented somewhere? If we just guess what to add, we will definitely not meet any requirements properly 😃

**Comment by JohannesLipp** [comment]
Plus, we need a definition of expected datatypes (or object types, i.e., classes) PLUS cardinalities.

**Comment by HaydarAk** [comment]
Did some brief research. Some ideas: 

- Jurisdication
- Legal Form
- distinguishment between different company names: legal name / trade name / prefered name. 
- company identifiers (via a generic `BusinessIdentifier` class (similar to `gax:BusinessIdentifier`) 
- VAT (Value Added Tax)

I'll check the existing fields of the participant again. Maybe we could extend our model, e.g. for the company address (`ids:Site`).

**Comment by HaydarAk** [comment]
**Suggestion for new properties**:

| Property             | Value                           | Cardinality | Example                                                       | Existing standards | Comment                                  |
|----------------------|---------------------------------|-------------|---------------------------------------------------------------|--------------------|------------------------------------------|
| Jurisdication        | String / ISO Code               | 1           | DE, FR, PL                                                    | ISO 3166-2         |                                          |
| Legal Form           | String / ISO Code               | 0..1        | 6QQB = Aktiengesellschaft (DE) XLZV = Registered Society (UK) | ISO 20275          |                                          |
| Legal Name           | String / LangString             | 1           |                                                               |                    | To distinguish between different names. Prefered name / trade name to display in the IDSA, the legal name everything related to e.g. billing and stuff. |
| Trade Name           | String / LangString             | 0..*        |                                                               |                    |                                          |
| Prefered name        | String / LangString             | 0..1        |                                                               |                    |                                          |
| Company Identifier   | like GAIA-X BusinessIdentifier | 0..*        | like GAIA-X BusinessIdentifier                               |                    |  Simple identification / classification system with a class like `ids:BusinessIdentifier` "identifier type" and "identifier value"                                         |
| VAT ?                |                                 | 0..1        |                                                               |                    |                                          |
| Business sector(s) ? | ???                             | 0..*        | ???                                                           | NACE 2, ISIC, …    |                                          |

**Comment by HaydarAk** [comment]
Changes:

| Class    | Property – old | Value Type - old | Property – new     | Value Type - new | Cardinality |
|----------|----------------|------------|--------------------|------------|-------------|
| ids:Site | ids:address    | xsd:string | vcard:countryName  | xsd:string | 0..1        |
|          |                |            | vcard:locality     | xsd:string | 0..1       |
|          |                |            | vcard:postal code  | xsd:string | 0..1        |
|          |                |            | vcard:region       | xsd:string | 0..1       |
|          |                |            | vcard:streetAdress | xsd:string | 0..1        |
