### ISSUE TITLE
HTTP response for asynchronous Messages using Multipart

### ISSUE THREAD

**Issue by stefkoslowski** [International-Data-Spaces-Association/InformationModel#421]
In the Scenario Contract Negotiation as described in Step 2 of the IDS Handshake an asynchronous message is sent. Since HTTP is synchronous by definition this leaves us with the question as to what response should be send back in this specific case. Shall we just respond with a 200 status code or send another Infomodel message such as a NotifcationResponseMessage?

**Comment by HaydarAk** [comment]
From an Information Model perspective, there are 2 response types in normal cases:
- Most `Request`  messages have a `Response` counterpart. They should be used, if possible. 
- If a direct response is not possible: `ids:RequestInProcessMessage` can be used. It can be treated as a `HTTP 102`, more or less. This may be used if e.g. a consumer requests an artifact and, as a provider, one needs to generate the artifact first and therefore cannot send the desired response directly. 
https://github.com/International-Data-Spaces-Association/InformationModel/blob/40f029a1ffc0846dfbe720e6268c07d5db68a898/taxonomies/Message.ttl#L321-L324


We also have the `ids:MessageProcessedNotificationMessage`, which can be seen similar to a 
https://github.com/International-Data-Spaces-Association/InformationModel/blob/40f029a1ffc0846dfbe720e6268c07d5db68a898/taxonomies/Message.ttl#L330-L333

**Comment by HaydarAk** [comment]
I hope my explanation helped you. If not, feel free to reopen the issue for further questions and so on :)
