### ISSUE TITLE
Cardinality of ids:sovereign?

### ISSUE THREAD

**Issue by clange** [International-Data-Spaces-Association/InformationModel#426]
A question that came up in the Catalogue work package of GAIA-X Federation Services: what is the cardinality of `ids:sovereign`? We always speak of "the owner" or "the sovereign", but we never restricted the cardinality, even though we have the technical means to do so.
* Did we forget to do so?
* Or did we intend that a resource might have multiple sovereigns?

**Comment by HaydarAk** [comment]
This is our current cardinality restriction.
**no min count, max count = 1**
https://github.com/International-Data-Spaces-Association/InformationModel/blob/2dc8d3be99971ac0ec6740714348f243ca18835a/testing/content/ResourceShape.ttl#L68-L75
