### ISSUE TITLE
Literal values conventions

### ISSUE THREAD

**Issue by jpullmann** [International-Data-Spaces-Association/InformationModel#46]
Make the assumptions on and handling of literals explicit. Document where "simple literals" are fine or further annotation by datatype and language tag is required (e.g. because of transformation into Java representations).

**Comment by jlangkau** [comment]
!!!

**Comment by jpullmann** [comment]
Relates to #56, explicit decision on whether a literal has to be typed..

**Comment by sebbader** [comment]
I'd say we have significantly improved the quality assurance and validation processes in the meantime, also regarding typed literals (see SHACL shapes). Therefore, I close the issue.
