### ISSUE TITLE
List and evaluate every usage of external classes or properties

### ISSUE THREAD

**Issue by JohannesLipp** [International-Data-Spaces-Association/InformationModel#461]
We need a list of every external class and property used in the IDS information model and an evaluation if the usage is redundant (i.e., not adding any benefit). 

Expected result (1x for classes, 1x for properties):
| File | IDS class/property name | External class/property name | Evaluation* |
|---|---|---|---|
|  Rule.ttl | ids:Permission  | odrl:Permission  | r (no beneficial addition made) |
| ...  | ...  | ...  | ...  |

(*e.g., "redundant"(r) or "non-redundant"(nr) or partially redundant (pr) - please add comments to clarify the choice, if required)

Suggested approach: You could clone the IDS information model (master or develop branch) and use the Notepad++ "search in files" feature with regular expressions as follows:
![image](https://user-images.githubusercontent.com/15930331/122802684-ece8c480-d2c5-11eb-9ca2-c0eee06411f2.png)

Traverse through the results, but please ignore copies of ontologies by simply collapsing them from the search result window. See the bottom at the screenshot: 
![image](https://user-images.githubusercontent.com/15930331/122802828-24577100-d2c6-11eb-8553-dba58d3f5c18.png)

**Comment by JohannesLipp** [comment]
@HaydarAk @clange @changqin26 FYI; as discussed for T60.

**Comment by lcomet** [comment]
I am currently adding the evaluation of properties and external classes in this document: https://docs.google.com/spreadsheets/d/17RjLl6wkL_V2_jbf_vBfJ_77NgmENnf_tIfWZsNhr_Y/edit?usp=sharing

**Comment by JohannesLipp** [comment]
Update: That list is ~ 35 % finished and will be finalized by next week.

**Comment by JohannesLipp** [comment]
Also solves #413
