### ISSUE TITLE
Role of attribute "contractAnnex" in Contract

### ISSUE THREAD

**Issue by softabout** [International-Data-Spaces-Association/InformationModel#466]
A Contract (ContractAgreement, ContractRequest, ContractOffer) defines an attribute "contractAnnex", which is specified as type "ids:Resource". How can this attribute be interpreted?
- is it the subject of the contract, the asset that will be shared?
- is it just any supporting type of resource (additional descriptions, specifications, ...)?

<sub> Helmut Pfister <helmut.pfister@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

**Comment by juliapampus** [comment]
@HaydarAk @clange @JohannesLipp

**Comment by HaydarAk** [comment]
>is it just any supporting type of resource (additional descriptions, specifications, ...)?

Correct, that the idea behind it. To give the possibility to attach additional data (resources) to the contract. 


>is it the subject of the contract, the asset that will be shared?

The asset which will be shared is defined as part of the rules. E .g., 
`ids:Contract -> ids:permission -> ids:Permission (subclass of ids:Rule) -> ids:target -> ids:Asset` 
Resources as well as Representations and Artifacts are subclasses of ids:Asset.

**Comment by DominikPinsel** [comment]
Thanks for the answer! Maybe you can clarify this for me.

Are these examples of contract annex data?
- licenses
- natural language contract	
- how-to-use-data instructions

Could this imply that a contract with an annex cannot be accepted automatically, because it could contain natural language contract details?


<sub> Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by clange** [comment]
@sebbader maybe you are the best expert for clarifying this?

**Comment by sebbader** [comment]
Hello @DominikPinsel,

you can do it like that, yes. Please note however, that from an IDS Usage Control perspective, the values of an ids:contractAnnex are purely informative and non-normative. Meaning, if the declared ids:Permissions/ids:Prohibitions are not completely aligned with the (natural language) annex texts, no Usage Control engine can be expected to recognize this. It might however be useful to have them anyway, for instance for legal reasons.

**Comment by DominikPinsel** [comment]
Hello @sebbader,

thanks for your reply. I think this answers my question and I've gotten a better understanding how to use this property :) 
@softabout is currently working in another project, but I assume it's also ok for him if you close this issue now.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>
