### ISSUE TITLE
Broker vs. Connector

### ISSUE THREAD

**Issue by MoritzKeppler** [International-Data-Spaces-Association/InformationModel#469]
A broker is a subclass of a connector.
Does that mean that a broker can provide own artifacts? 
Or asking the other way round: A broker will just list own Resources in its self-description, not resources pushed to it by other connectors. Right?

<sub> Moritz Keppler <moritz.keppler@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by clange** [comment]
Interesting question. Indeed a Broker is a Connector, also [by its specification](https://internationaldataspaces.org/wp-content/uploads/IDSA-White-Paper-Specification-IDS-Meta-Data-Broker.pdf):
> In order to ensure the necessary interoperability and general interactions, an IDS Meta Data Broker (like the App Store) is also defined as a specialized IDS Connector. The communication between an IDS Connector and an IDS Meta Data Broker is based on the same principles as any other Connector-Connector communication within the International Data Spaces. Still, an IDS Meta Data Broker provides a collection of additional functionalities.

@sebbader can you help with the full answer to the question? Would it, e.g., be possible that a Broker assumed the Connector role and advertised some Resources to another Broker? If so, what would these Resources look like?

**Comment by sebbader** [comment]
Hello @MoritzKeppler,

that's true, a Metadata Broker could also publish its own Resources, and own access endpoints for instance. The difference can be outlined by using an ids:sovereign attribute pointing to the identifier of the Metadata Broker's operator. Then the client connectors can see that these resources are "owned" by the organization behind this Metdata Broker.
