### ISSUE TITLE
Extending ids:Frequency vocab

### ISSUE THREAD

**Issue by tomkxy** [International-Data-Spaces-Association/InformationModel#477]
In the MDP project at T-Systems we have the requirement for having additional frequency  definitions. We would we able to re-use the IDS Frequency class and the associated codes if the following codes would be added to frequency.ttl,. The following is just an abridged representation (only ID and comment):

idsc:DAILY_2
   a ids:Frequency;
    rdfs:comment "The event occurs every 12 hours."@en ;

idsc:EVERY_3_HOURS
    a ids:Frequency;
    rdfs:comment "The event occurs every 3 hours."@en ;

idsc:BIHOURLY
    a ids:Frequency;
    rdfs:comment "The event occurs every 2 hours."@en ;

idsc:HOURLY
    a ids:Frequency;
    rdfs:comment "The event occurs every hour."@en ;

idsc:EVERY_30_MINUTES
    a ids:Frequency;
    rdfs:comment "The event occurs 30 minutes."@en ;

idsc:EVERY_15_MINUTES
    a ids:Frequency;
    rdfs:comment "The event occurs 15 minutes."@en ;

idsc:EVERY_10_MINUTES
    a ids:Frequency;
    rdfs:comment "The event occurs 10 minutes."@en ;

idsc:EVERY_5_MINUTES
    a ids:Frequency;
    rdfs:comment "The event occurs 5 minutes."@en ;

idsc:EVERY_1_MINUTE
    a ids:Frequency;
    rdfs:comment "The event occurs minute."@en ;

**Comment by HaydarAk** [comment]
I'll take a look at that. 

Thank you for the contribution.

**Comment by HaydarAk** [comment]
Added the suggested changes to the code list of the `ids:Frequency` class in #483.
Thanks for the contribution :)
