### ISSUE TITLE
Title or Description field on representation or artifact level

### ISSUE THREAD

**Issue by tomkxy** [International-Data-Spaces-Association/InformationModel#479]
Dcat supports a title and description property on distribution level. Since I need to represent (map) from DCAT to IDS I was looking for those props on representation or artifact level. 

It seems that IDS does not foresee a title and description field on artifacts and representation? If that is right, I would suggest to consider this, since mapping from DCAT seems to be common requirement, at least in MDP it is.

**Comment by HaydarAk** [comment]
Good point. Should be easy to achieve and definitely a benefit.

**Comment by tomkxy** [comment]
Just saw that representation is a subclass of dcat:distribution. According to the DCAT spec title and description are formally already part of the ids:representation but according to my knowledge, they are not part of the generated Java classes.

**Comment by clange** [comment]
I think the solution would be as easy as 
```turtle
ids:Representation rdfs:subClassOf ids:Described
```

**Comment by HaydarAk** [comment]
Added the suggested changes to the `ids:Representation` class in #483. 

The IDS Information Model splits the dcat:Distribution into the ids:Representation and ids:Artifact. Therefore, it is not necessary to add title / description information to an artifact.
