### ISSUE TITLE
Extending ids:Frequency vocab

### ISSUE THREAD

**Issue by tomkxy** [International-Data-Spaces-Association/InformationModel#489]
Unfortunately, within the MDP project additional  codes for the frequency vocab are required (apart from the ones requested in an earlier issue).

Thus, in order to re-use the IDS Frequency class and the associated codes, if the following codes would be added to frequency.ttl,. The following is just an abridged representation (only ID and comment):

idsc:ONCE a ids:Frequency;
    rdfs:label "Only once"@en ;

idsc:UNKNOWN a ids:Frequency;
    rdfs:label "Unknown"@en ;

**Comment by HaydarAk** [comment]
Hi!

thanks for the contribution. It makes sense to add the `idsc:ONCE`. 
But I do not like the `unknown` to be honest. The term is not a frequency, if viewed from a semantics perspective. 

What is the difference between `idsc:UNKNOWN` and leaving the property empty / not using it ? I'd say there is no difference. Sure, from a developers perspective it is more pleasant to have a fixed value which states "unknown / none / ...". 

The properties which use ids:Frequency are not enforced via a min count. Therefore if there is no `ids:temporalResolution` or `ids:accrualPeriodicity` property listed for a ids:Resource this means the frequency is unknown :)

**Comment by tomkxy** [comment]
Makes sense what you are saying

**Comment by JohannesLipp** [comment]
@HaydarAk could you please add this property? Thank you in advance! This would solve this issue.

@tomkxy Instead of "Unknown" you could use the existing `idsc:IRREGULAR`?

**Comment by tomkxy** [comment]
As I said, I am fine with not having Unknown and just not filling that property. Your line of argument makes sense to me.
