### ISSUE TITLE
Add Cert Ontology as an external Reference

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/InformationModel#49]
The CERT ontology https://www.w3.org/ns/auth/cert# (draft only?) defines some concepts to link certificates and keys. SOLID (decentral social network by Tim Berners-Lee) also uses it here and there.

**Comment by jpullmann** [comment]
After a quick review this seems to be a focused, highly reusable model that addresses the IDS requirements w.r.t identity an trust.  +1 for integrating into the Connector and Participant descriptions.

**Comment by sebbader** [comment]
I agree with @HaydarAk, this issue is not relevant anymore.
