### ISSUE TITLE
Refactor identified refactoring options for the IDS information model

### ISSUE THREAD

**Issue by JohannesLipp** [International-Data-Spaces-Association/InformationModel#490]
General requirements from the Java lib:
- We need at least need class definitions for every class in the ontology - also for external classes.
- All SHACL properties should have `sh:name` and `sh:description`.
- @HaydarAk please clarify with @sebbader if we can upgrade the CodeGen to read (external) classes from SHACL files, so that @maboeckmann can implement this

**Comment by JohannesLipp** [comment]
refers to #461

**Comment by JohannesLipp** [comment]
@maboeckmann PUSH

**Comment by JohannesLipp** [comment]
@maboeckmann push

**Comment by JohannesLipp** [comment]
@changqin26 please invite Pascal to this repository and ask him about this issue - thank you!

**Comment by JohannesLipp** [comment]
@pnlinden

**Comment by JohannesLipp** [comment]
@pnlinden Could you please comment on our question above ASAP? Thank you.

**Comment by pnlinden** [comment]
I tested a minimal example for your proposal. When the "helper files" are added for the removed classes in the form you proposed above, we need to make a few adjustments in the CodeGen Tool, but then this should be fine.

**Comment by JohannesLipp** [comment]
Thank you very much for your review!

My comments in order to your four bullets:
- Agree with your approach, if possible
- Agree, that prefix URI should be consistent among all files
- Good point! Agree, we should skip the `skos:Concept` for properties as it is semantically wrong
- That will require some effort on our side, but we will do that as it is required for your CodeGen - deal!

@lcomet could you please update the branch as requested? Thank you in advance!

**Comment by pnlinden** [comment]
Thank you for the changes! I just noticed one more thing while looking through the output of the CodeGen Tool:
The classes in the helper file used to be ids-classes. As such, we sometimes had some hierarchical statements, e.g. `ids:Rule rdfs:subClassOf ids:Described ;`, `ids:Duty rdfs:subClassOf ids:Rule ;`, ... This kind of relation does not exist anymore in the helper file, such that e.g. the properties of `odrl:Rule` are not passed to `odrl:Duty`. But I would recommend that we keep this relations between the classes. That would mean, I would like to propose one more (this time small) change to you:
This would include the following additions in the helper file:
- `foaf:Agent rdfs:subClassOf ids:Described ;`
- `odrl:AssetCollection  rdfs:subClassOf odrl:Asset ;`
- `time:Instant rdfs:subClassOf time:TemporalEntity ;`
- `time:Interval rdfs:subClassOf time:TemporalEntity ;`
- `odrl:Rule rdfs:subClassOf ids:Described ;`
- `odrl:Permission rdfs:subClassOf odrl:Rule ;`
- `odrl:Prohibition rdfs:subClassOf odrl:Rule ;`
- `odrl:Duty rdfs:subClassOf odrl:Rule ;`

I think, this should be all the "lost" subclass relation. But please check that I didn't miss anything.

**Comment by lcomet** [comment]
@pnlinden Please note that the requested changes regarding the missing subclass relations have been implemented under commit 78da3cd

**Comment by pnlinden** [comment]
Thank you! I tested the new version and it seems to be all good now! The branch for the CodeGen Tool is prepared and when the update to InfoModel 5.0.0 comes around, we can merge that branch accordingly.

**Comment by riannella** [comment]
As a note, SKOS allows an owl:objectProperty to also be an skos:Concept:
  https://www.w3.org/TR/2009/REC-skos-reference-20090818/#L896
