### ISSUE TITLE
Fix Widoco ontology visualization

### ISSUE THREAD

**Issue by JohannesLipp** [International-Data-Spaces-Association/InformationModel#497]
The visualization at https://w3id.org/idsa/core is broken, please fix it. Thanks! 

![image](https://user-images.githubusercontent.com/15930331/129755613-21089f4a-7e5c-47fe-9d82-ff2c2bcd2840.png)

**Comment by lcomet** [comment]
Solved by changes under commit dd03c0d

**Comment by JohannesLipp** [comment]
Thank you very much for solving this!
