### ISSUE TITLE
Picture "all_classes.png" broken in release 4.1.0

### ISSUE THREAD

**Issue by bastianleirpo** [International-Data-Spaces-Association/InformationModel#500]
In the current release (https://github.com/International-Data-Spaces-Association/InformationModel/releases/tag/v4.1.0) the file "all_classes.png" is broken:

![all_classes (4)](https://user-images.githubusercontent.com/22075788/132313316-3eecbbc0-900b-474e-85ae-647353550a6e.png)

**Comment by pnlinden** [comment]
I recreated the all_classes.png and updated the release (see [Release v4.1.0](https://github.com/International-Data-Spaces-Association/InformationModel/releases/tag/v4.1.0) ).
