### ISSUE TITLE
Fix OOPS link on Widoco page

### ISSUE THREAD

**Issue by JohannesLipp** [International-Data-Spaces-Association/InformationModel#502]
![image](https://user-images.githubusercontent.com/15930331/134302394-7b142bd6-0061-476d-8dc2-9739ffb87d98.png)

The OOPS link on the Widoco page links [here](https://international-data-spaces-association.github.io/InformationModel/docs/OOPSEvaluation/OOPSeval.html#) but the correct URL is [this](https://international-data-spaces-association.github.io/InformationModel/docs/OOPSevaluation/OOPSeval.html#).

Please replace `OOPSEvaluation/OOPSeval.html` with `OOPSevaluation/OOPSeval.html` in our automatic pipeline to fix this, thanks!

**Comment by lcomet** [comment]
Fixed with commits c3a23ccabb696ef64e3844b0d97c6bd8ba548b66 4d6271b94243ec7a34af29e48ffe02163895c656 and 1f99ce3169b7b3c3a94b5fac58518c1871892d33
