### ISSUE TITLE
Add ids:Catalog as a subclass of odrl:AssetCollection

### ISSUE THREAD

**Issue by changqin26** [International-Data-Spaces-Association/InformationModel#513]
make ids:Catalog a subclass not only of dcat:Catalog but also of odrl:AssetCollection (alignment of DCAT and ODRL not only on single-resource but also on collection level)

**Comment by changqin26** [comment]
we don't have ids:Catalog anymore. It is replaced by dcat:Catalog. The definition of dcat:Catalog is: 
A curated collection of metadata about resources (e.g., datasets and data services in the context of a data catalog). it already contains the aspect of "collection of metadata", therefore, I think we don't need to do the alignment between dcat:Catalog and odrl:AssetCollection anymore. 

What is your opinion? @clange

**Comment by JohannesLipp** [comment]
Please reopen if it still applies.
