### ISSUE TITLE
Relationship between ContractOffer and Resource

### ISSUE THREAD

**Issue by DominikPinsel** [International-Data-Spaces-Association/InformationModel#522]
Hello everyone,

I've got a question regarding the `Resource` and `ContractOffer`.

I'm assume that a `Resource` is the thing I want to exchange. For example if I have weather data for different cities, I would create a `Resource` object for each city. And this `Resource` then has it different `Representations` and `Artifacts` of the data.
For me it gets confusing when I want to create a `ContractOffer` for the weather data of the 10 largest cities in Germany. The part I understand is that I now have create 10x `Resource` and 1x `ContractOffer`. But how do I represent the relationship between them?

- Is it correct to put the `ContractOffer` into each `Ressource`?
- Is it correct that the `ContractOffer` of one `Resource` may reference artifacts of other `Resources`?

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by changqin26** [comment]
`Is it correct to put the ContractOffer into each Ressource?`
Yes. You can reference a ContractOffer from the line 65 to 103 in a Resource template https://github.com/International-Data-Spaces-Association/InformationModel/blob/develop/examples/domain-specific-semantics-using-SHACL/TEMP_RESOURCE.ttl.

**Comment by changqin26** [comment]
`Is it correct that the ContractOffer of one Resource may reference artifacts of other Resources?`
Yes. In IDS Infomodel, we use ids:target to point from one Rule inside a ContractOffer to its Resource artifact. The range of ids:target should be a URI representing either an Asset or an AssetCollection. When it is pointing to an AssetCollection, then it references not only one Resource but also other Resources.

**Comment by DominikPinsel** [comment]
@changqin26 Thanks for your reply. That's really interesting. I must say, that I never thought about AssetCollection IDs in Contracts until now.
So to stay with the weather example. The best way to do this would be:
- Create 10x `Resource` for each city
- Create 1x `AssetCollection`, containing each `Resource`
- Create 1x `ContractOffer`, targeting the `AssetCollection`
- Put the `ContractOffer` into each `Resource`

**Comment by changqin26** [comment]
Yes, in this way, the content of the `ContractOffer` will apply to each `Resource` in the `AssetCollection`.
