### ISSUE TITLE
Participant.legalForm is mandatory but should be optional

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/InformationModel#534]
https://github.com/International-Data-Spaces-Association/InformationModel/blob/018abfe8a1e96ac842cccc99d4ae1dddfdc838cc/testing/participant/ParticipantShape.ttl#L110 states that Participant.legalForm has cardinality min 1 and max 1 --> is mandatory. However, there are many use cases where I want to speak about an IDS Participant without even knowing his legalForm. Therefore, I am voting to remove the min 1 line.

**Comment by JohannesLipp** [comment]
That might be inspired by recent Gaia-X development, which however only introduced this for provider but not for participants in general. We might therefore set this to optional (e.g., `sh:minCount 0`) in this general context indeed.

**Comment by changqin26** [comment]
I will create a branch to adjust this.
