### ISSUE TITLE
Enable Java Library Generation for Domain-specific Extensions

### ISSUE THREAD

**Issue by JohannesLipp** [International-Data-Spaces-Association/InformationModel#545]
Context: 

- Recent PR #504 to reuse external concepts directly
- Soon-to-be-merged PR #543 that provides a hands-on manual for developers

Suggested steps for domain- or application-specific extensions are:

1. Decide what to model
2. Use the IDS Information Model as a basis for describing the different components
3. Extend the IDS Model with the local/custom definitions and restrictions

@mkollenstart raised the following request at the Q1/22 IDS Plugfest, which was boosted by @abhishekmaha-tno . Thank you again for this valuable feedback!

**Task: Add support for a step 4., which enables developers to generate a tailored version of the Java library based on domain-specific extensions from steps 1-3.**

**Comment by sebbader** [comment]
Hi @JohannesLipp, does step 4 mean that developers shall be in the position to run the Java model generator by themselves? If so, the IP of the generator is, for now, still exclusively with Fraunhofer and I am not sure if it will be released
 soon/at all.

**Comment by JohannesLipp** [comment]
@sebbader thank you for raising this. I too have no precise approach for that in mind yet. Since the Java library is of central use for many developers, we still need to find some way to enable people to extend it. If there is no self-maintained way in the near future, the only solution seems to be a semi-manual way including Fraunhofer-IP-responsible persons correct?

**Comment by JohannesLipp** [comment]
The answer to my question is YES.
