### ISSUE TITLE
Remove Infomodel Maven Java-Artifact 4.3.0

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/InformationModel#554]
There seems to be a version 4.3.0 that resulted from a wrong sem-versioning (see release date). 
See https://maven.iais.fraunhofer.de/ui/native/eis-ids-public/de/fraunhofer/iais/eis/ids/infomodel/java/
It would be great to remove this version to avoid confusion. Especially Dependabot-Updates rely on version names, instead of timestamps. Thus, one could tap into this versioning-issue by mistake.

**Comment by pnlinden** [comment]
Version 4.3.0 is deleted from the maven artifactory. As it was identical to version 4.2.3, I added a note [here](https://github.com/International-Data-Spaces-Association/Java-Representation-of-IDS-Information-Model/blob/main/Changelog.md) to switch to that previous version if for some reason anyone still had a dependency to version 4.3.0 .
