### ISSUE TITLE
dcat:accessRights in UsagePolicies

### ISSUE THREAD

**Issue by PHochmann** [International-Data-Spaces-Association/InformationModel#556]
Since DCAT already uses DublinCore's RightsStatement, ids:UsagePolicyClass could be aligned with it.

**Comment by changqin26** [comment]
dct:accessRights is the property of dcat:Distribution, which is already existed in our ontology. In the dcat, it has: dcat:Distribution dct:accessRights dct:RightsStatement. Does it mean that we should replace ids:UsagePolicyClass with dct: RightsStatement? @hosseinzadeha Can you please help us how to align this? For now, we just use ids:UsagePolicyClass describing DataApp here https://github.com/International-Data-Spaces-Association/InformationModel/blob/af271b0d1773316c4dcead36fc9b5b1de80febdf/model/content/DataApp.ttl#L46.

**Comment by hosseinzadeha** [comment]
@PHochmann Hi, it is not clear to me what you mean by aligning these two concepts. For now, what I see is that the dct:RightsStatement addresses Access Control issues while the ids:UsagePolicyClass refers to the Usage Control restrictions such as Count the usage, notify a Data Provider about the usage, Delete the data after the usage, etc. These usage restrictions cannot simply be expressed by Right Statements.
Could you please give me an example (use case) of how you want to align dct:RightsStatement and ids:UsagePolicyClass?

**Comment by PHochmann** [comment]
@hosseinzadeha My proposal of using dct:accessRights was wrong, DCAT explicitly says that dct:accessRights is only to be used to describe access and not usage, dct:rights would be the right property that catches all other usages (see https://www.w3.org/TR/vocab-dcat-2/#license-rights)
On the other hand, I understand dct:RightsStatement to be generic about every type of rights. Thus, I'd suggest replacing ids:UsagePolicyClass by dct:RightsStatement in each instances and to replace ids:supportedUsagePolicies with dct:rights. I don't have an example since I'm no domain expert, my goal is replace ids vocbulary with existing ontologies' vocabulary.

**Comment by hosseinzadeha** [comment]
Policy Classes are used for tracking which kinds of usage restrictions can be enforced. It is a Usage Control concept which can be put out of Information Model but cannot be replaced by "dct:rights". Maybe we could arrange a meeting and discuss about it. @Brandstaedter could join too.

**Comment by PHochmann** [comment]
Thanks for your response! Closing this issue as `dct:rights` does not apply here.
