### ISSUE TITLE
Decide upon a formal modelling and differentiation of content instances (artefacts)

### ISSUE THREAD

**Issue by jpullmann** [International-Data-Spaces-Association/InformationModel#57]
According to a "traditional" interpretation instances of a resource representation (artefcts) "share the same intellectual content in different physical formats" [[1](https://www.w3.org/TR/vocab-adms/#pc_AssetDistribution)]. In contrast, there are frequent examples of resources materialized as lose _collection_ of files or _series_ of files ordered according to particular content dimension (day, area etc.), example `TrainDelays_Jan_2019.csv`, `TrainDelays_Feb_2019`. Individual file are at most distinguished by semi-structured file names or textual descriptions. Inspired by [Data Cube Vocabulary](https://www.w3.org/TR/vocab-data-cube/) descriptive parameters were used to formally express the distinguishing dimensions, see example [DATA2](https://github.com/IndustrialDataSpace/InformationModel/blob/develop/examples/DATA2.ttl). This benefits from re-using the API Parameters concept. On the contrary, descriptive predicates like `dct:spatial` or `dct:temporal`exist, but are currently applied to the abstract resource only. Evaluate these and alternative approaches to model and semantically differentiate resource instances.

**Comment by JohannesLipp** [comment]
Closed due to inactivity.
