### ISSUE TITLE
Remove outdated generated documentation from main

### ISSUE THREAD

**Issue by JohannesLipp** [International-Data-Spaces-Association/InformationModel#572]
The [main branch contains outdated Widocu content](https://github.com/International-Data-Spaces-Association/InformationModel/tree/main/docs), but the most recent versions will always be in [the gh-pages branch](https://github.com/International-Data-Spaces-Association/InformationModel/tree/gh-pages/docs). 

Please remove the `docs/` directory from `main` and exclusively maintain it on `gh-pages` from now on to avoid confusion. Thanks!

**Comment by lcomet** [comment]
Solved with 99166e1c21e14dfc48e0aecded4203da7a842ffa
Associated PR  #610 to also remove outdated documentation from the "develop" branch.
