### ISSUE TITLE
Document used licenses from scripts

### ISSUE THREAD

**Issue by JohannesLipp** [International-Data-Spaces-Association/InformationModel#579]
Especially the directories [docs/config](https://github.com/International-Data-Spaces-Association/InformationModel/tree/develop/docs/config/) and [utils](https://github.com/International-Data-Spaces-Association/InformationModel/tree/develop/utils/) and examples.

Please comment here and document via mail to Anil Turkmayali <Anil.turkmayali@internationaldataspaces.org>

Deadline = 29.07.

**Comment by PHochmann** [comment]
docs/config/widoco.py:
* requests: Apache Software License (Apache 2.0)

docs/insert_eval_results.py:
* BeautifulSoup: MIT license

utils/test_rewrite_rules.sh:
* curl: FOSS, custom license https://curl.se/docs/copyright.html

examples/queries-using-sparql/:
* Jena: Apache Software License (Apache 2.0)

examples/rdf-validation-using-shacl/:
* Jena: Apache Software License (Apache 2.0)
* slf4j: MIT license
* TopBraid SHACL: Apache 2.0
