### ISSUE TITLE
Broker query capabilities specification

### ISSUE THREAD

**Issue by cmader** [International-Data-Spaces-Association/InformationModel#58]
A Broker needs to publish the query languages it "understands" when receiving BrokerQueryMessages. Furthermore, brokers need a way to make the client know how to formulate his queries because each broker is free to its own data model for storing connector registrations internally. Options are to
*  publish the internal schema
* prescribe a schema
* define a special broker query language

What solution should we go for?

**Comment by jpullmann** [comment]
agreed, +describe the assumptions / conventions of the "default" implementation, e.g. by linking from  broker's  [Catalog](https://github.com/IndustrialDataSpace/InformationModel/blob/develop/model/infrastructure/Catalog.ttl) to individual resources (`offer` or `request`) one may locate the resources even when metadata is partitioned into individual named graphs (transparent persistence feature)

**Comment by jpullmann** [comment]
For SPARQL endpoints consider the API description [SPARQL 1.1 Service Description](https://www.w3.org/TR/sparql11-service-description/)

**Comment by cmader** [comment]
for simplicity, I'd suggest a simple optional property ids:queryLanguage with domain ids:Broker and range ids:QueryLanguage. This way, the Broker could indicate the query languages it supports. The current values in ids:QueryLanguage should be extended, e.g., with a JSONPath entry. if the queryLanguage propery is missing in a Broker's self description, this means that he cannot handle messages of type BrokerQueryMessage.
In addition, I'd suggest an optional property ids:queryModel with domain ids:Broker and range xsd:string, that holds a textual representation of the data structure against queries are performed. This textual representation should be good enough for humans to get an idea how queries should be formulated.

**Comment by sebbader** [comment]
+1 to also align it with the AppStore requirments, similar to #60

**Comment by JohannesLipp** [comment]
Closed due to inactivity. Please comment & re-open if required.
