### ISSUE TITLE
InfrastructureComponentShape defined twice

### ISSUE THREAD

**Issue by PHochmann** [International-Data-Spaces-Association/InformationModel#588]
The InfrastructureComponentShape is defined once in `testing\infrastructure\ComponentShape.ttl` and once slightly different in `testing\infrastructure\InfrastructureComponentShape.ttl`. The latter (InfrastructureComponentShape.ttl) seems to me to be the correct version, the other (ComponentShape.ttl) we should perhaps delete. It is not critical now, only in the long run it may lead to confusion and unwanted behavior.

**Comment by lcomet** [comment]
Checking the `default` branch, there is no such a` testing\infrastructure\ComponentShape.ttl`, only a t`esting\infrastructure\InfrastructureComponentShape.ttl`. Therefore, we can close this issue.
