### ISSUE TITLE
Clarification regarding domain commitment 

### ISSUE THREAD

**Issue by kvistgaard** [International-Data-Spaces-Association/InformationModel#606]
The following claim is made in the Scope section:

> The Information Model is a generic model, with no commitment to any particular domain

At the same time just above:

> Information Model describes essential properties of Industrial Data Space entities

It seems that domains-specific is meant only in the context of "Industrial Data Space" which is by itself a domain, distinct from other domains such as Public Administration and Healthcare and their respective dataspaces.

Having this mind, it would be good to clarify
1. The "no commitment" statement
2. The applicability of the information model outside the Industrial Data Space

**Comment by JohannesLipp** [comment]
Hi @kvistgaard , thanks for pointing this out! Could you please link the place where the second statement (on the Industrial Data Space) is made? The IDS initially stood for "Industrial DS", but was later renamed to "International DS" to underline its extended scope. Maybe we forgot to update this in some places. Thank you!

**Comment by kvistgaard** [comment]
Line: [InformationModel/docs/sections/introduction-en.html at develop · International-Data-Spaces-Association/InformationModel](https://github.com/International-Data-Spaces-Association/InformationModel/blob/develop/docs/sections/introduction-en.html#L1)

Annotated screenshot:

![image](https://github.com/International-Data-Spaces-Association/InformationModel/assets/7572721/e201ad9c-2d65-4e70-a0d1-4f4f2b8ccf46)

**Comment by JohannesLipp** [comment]
Thank you! We will look into this (see below).

@kvistgaard FYI https://w3id.org/idsa/core is a more convenient and more up-to-date link to consume these documentations.

@lcomet We should update all documentations from "Industrial Data Spaces" to "International Data Space".

**Comment by kvistgaard** [comment]
@JohannesLipp 
> @kvistgaard FYI https://w3id.org/idsa/core is a more convenient and more up-to-date link to consume these documentations.

yes, that's what I'm using but since you asked "please link the place" , it was then that I looked for the source to point to.

**Comment by lcomet** [comment]
Thank you for reporting this issue. It is now solved by https://github.com/International-Data-Spaces-Association/InformationModel/commit/4ce4fa25dbd24b56a063a5d81c5dcbcfffc07d56 and https://github.com/International-Data-Spaces-Association/InformationModel/commit/e6cfbe9087bf7e1545ccd95bda9ae229cf346ce3
