### ISSUE TITLE
Provide UsagePolicyTemplateIdentifiers into the InfoModel

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/InformationModel#61]
The Usage Policy Language provides several templates. IDS participants need to be enabled to refer to these templates. Therefore, unique identifiers should be defined by Information Model. Probably as part of the /codes/ directory?

**Comment by jpullmann** [comment]
Agree with recording such "policy blueprints", we'd elaborate the model. The templates themselves are not really plain "codes", rather shared artifacts. They might need some parameterization to become useful? Same holds for re-usable query or data templates. What about creating a new class e.g. Template / PolicyTemplate etc. like [SPIN Template](https://www.w3.org/Submission/2011/SUBM-spin-modeling-20110222/#spin-templates) and provide instances of them in a "templates" folder.

**Comment by sebbader** [comment]
Sounds good. I will come up with some suggestions beginning of next week.

**Comment by sebbader** [comment]
wrong button...

**Comment by sebbader** [comment]
I also need a property linking from the contract to the template it corresponds to. For instance:
`:TimeRestrictedContractOffer1  ids:refersTo  ids:TimeRestrictedContractOfferTempalte .`

**Comment by sebbader** [comment]
This ticket has been solved in a first version, although a further iteration is required. This will be done in an additional ticket.
