### ISSUE TITLE
Add a reference to the repository in the human-friendly version 

### ISSUE THREAD

**Issue by np00** [International-Data-Spaces-Association/InformationModel#74]
URL: http://ids.semantic-interoperability.org/

**Comment by np00** [comment]
Ok, I just found it in the Introduction :) 

However, wouldn't it be nice to put it on top, right after "Download Serialization"? 
It would help those visitors who like to quickly download the source and import it into their favourite ontology exploration tool.

**Comment by clange** [comment]
Actually – maybe we need a new issue for this – this whole document should either be taken down or updated, as it is quite outdated. However, parts of it seem to have been created manually, so this might be hard. Who owns the domain? Steffen Lohmann? @sebbader could you maybe find out?

**Comment by sebbader** [comment]
Hi Christoph, yes, I think its his domain. However, the more accurate documentation is here: https://industrialdataspace.github.io/InformationModel/docs/index.html 
Redirects at the namespace location (https://w3id.org/idsa/core) point also to this side.

**Comment by sebbader** [comment]
Update: I have requested to change http://ids.semantic-interoperability.org/ to redirect to https://w3id.org/idsa/core . Solving this will solve this ticket in my view.

**Comment by HaydarAk** [comment]
Redirect looks good. 👍
