### ISSUE TITLE
remove or update the references section text in the human-friendly version

### ISSUE THREAD

**Issue by np00** [International-Data-Spaces-Association/InformationModel#75]
URL: http://ids.semantic-interoperability.org/#ref

There seems to be a placeholder text in place.

**Comment by sebbader** [comment]
I see that one as a part of the more general issue of updateing the html docu and moving it to https://w3id.org/idsa/...

**Comment by HaydarAk** [comment]
We did a major overhaul of the documentation (https://w3id.org/idsa/core). 

This should have fixed this issue.
