### ISSUE TITLE
Provide a full dereferencable human-friendly documentation

### ISSUE THREAD

**Issue by np00** [International-Data-Spaces-Association/InformationModel#76]
There seem to be a couple of issues: 

(1) 
The Information Model is not (yet?) deployed on: [https://schema.industrialdataspace.org/](https://schema.industrialdataspace.org/). 

But there exist an (old?) one on: [http://ids.semantic-interoperability.org/](http://ids.semantic-interoperability.org/)

(2) 
The IRI of the Information Model should be probably extended with the hashtag symbol **#**:
`https://schema.industrialdataspace.org/#`

(3)
The existing deployment on [http://ids.semantic-interoperability.org/](http://ids.semantic-interoperability.org/) could be a bit improved:  

(3a) Resource names show up twice in the IRI: 
`http://ids.semantic-interoperability.org/#dataAsset/DataAsset`

(3b) A resource reference provided for example in the Class List: http://ids.semantic-interoperability.org/#classes is not identical with the actual resource IRI: 

Resource Reference IRI in the Class List: 
`http://ids.semantic-interoperability.org/#dataAsset/DataAsset` <- hashtag with old IRI
Actual IRI:` https://schema.industrialdataspace.org/dataAsset/DataAsset
` <- no hashtag

**Comment by sebbader** [comment]
As the ids namespace has changed to https://w3id.org/idsa/, a compelete update of the docu is necessary. While several documents have been created (e.g. Information Model in RAM3), the ontology docu needs to be moved and updated accordingly.

**Comment by sebbader** [comment]
@np00 please checkout the new docu: https://industrialdataspace.github.io/InformationModel/

**Comment by clange** [comment]
Now that we have #93 I think this will fix part of this problem once it has been fixed.

**Comment by HaydarAk** [comment]
New docu (https://w3id.org/idsa/core) these problems
