### ISSUE TITLE
Duplication of Hosts for Endpoints in SelfDescription

### ISSUE THREAD

**Issue by mkollenstart** [International-Data-Spaces-Association/InformationModel#80]
In connector self-descriptions with a lot of dynamic endpoints, e.g. when mapping a REST server to the Information Model, the endpointHost property is added to all endpoints.

This makes the self-description unnecessary verbose.

My suggestion would be to reference the endpointHost property of Endpoints by url, linking to the hosts defined at the connector level.

**Comment by sebbader** [comment]
This one needs to go up the prio list. I just did a similar thing as you, @mkollenstart , and the Endpoint modelling is really a pain.

**Comment by sebbader** [comment]
I assigned it the `4.0.0` label as we need to do some breaking changes here.

**Comment by sebbader** [comment]
Solved with #310 .
