### ISSUE TITLE
InfoModell into Certification Criteria

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/InformationModel#98]
We need to add requirements for IM support (which versions, which features, mandatory and optional attributes, etc.) into the IDS Ready certification list.

**Comment by HaydarAk** [comment]
@sebbader  Still ongoing?

**Comment by DennisKubitza** [comment]
For the Broker the Requirements all mentions of InformationModell:

B 026 | An IDS Meta Data Broker must provide a Self-Description document at <scheme>://<authority>[:port][/path/to/broker]/ according to the IDS Information Model version it announced.

B 029 | An IDS Meta Data Broker must provide capabilities to persistently store meta
data conforming to the IDS Information Model. The conforming Information model has to be at least of version 3.0.0. 

B 039 | An IDS Meta Data Broker will provide a self-information like any other connector. In difference to other connector Connectors theis self-information  of an IDS Meta Data Broker has to be supplied at a specified URL (http(s)://<broker.authority>[:port]/<path to broker root>) and gives additional information about the index service. This information contains aditionally at least additionally for :  supported (native) query languages  supported identity providers (like connector Connector)  available add-on service (like data endpoints)  publication of local index service rules (→ B18)

B 040 The attributes of B39 are specified in the IDS Information Model and have to be delivered in an RDF serialization.

B 042: An IDS Meta Data Broker must announce the supported IDS Information Model versions for outbound and inbound messages through its Self-Description document. 

B 047 An IDS Meta Data Broker must reject messages if they do not conform to the IDS Information Model specifications and should send a proper RejectionMessage in that case. 

B 057| An IDS Meta Data Broker must only support one IDS Information Model versions for outgoing messages.
-- | --
________

I think we can also Take B026, B042, B047 for connectors. What do you think ? @HaydarAk @sebbader

**Comment by JohannesLipp** [comment]
Closed due to inactivity. Please re-open and comment a more recent state if required. Thank you!
